### ISSUE TITLE
How to get rid of "Loading a theme can run Lisp code.  Really load? (y or n) " message?

### ISSUE THREAD

**Issue by ghost** [Malabarba/smart-mode-line#100]
This message pops up every time when I open emacs. ("Loading a theme can run Lisp code.  Really load? (y or n)")

Even after  I choose "Treat this theme as safe in future sessions? (y or n) y".

I am using emacs-24.4.

**Comment by Tinker-S** [comment]
Please see the description of `load-theme`, there has a `NO_CONFIRM` parameter in the optional, so you just need to use `(load-theme tango t)` and there won't be any prompt. The key point is add `t` param.

**Comment by Malabarba** [comment]
@Tinker-S Yes, that's what the `sml/no-confirm-load-theme` option does. It tells `sml` to pass the `NOCONFIRM` argument to `load-theme`. It would be a bad idea for sml to do this by default, as I would be exposing the user to a security risk. So I leave it as an option for the user to turn on.
It's a small thing, but I'd rather explain to people that their `.emacs` file has issues than hide behind a security hole.

**Comment by idanko** [comment]
Another option is to treat all themes as safe ones by `(setq custom-safe-themes t)`.
