### ISSUE TITLE
light-colored variant of powerline theme

### ISSUE THREAD

**Issue by dakrone** [Malabarba/smart-mode-line#103]
It would be really nice if smart-mode-line's powerline theme supported a light-colored background variant of the powerline theme, unfortunately right now using the powerline theme looks like:

![screen shot 2014-12-01 at 5 06 17 pm](https://cloud.githubusercontent.com/assets/19060/5248540/60f09f74-797c-11e4-9bc1-7712164ce528.png)

The white inactive border styling makes reading the inactive buffer's modeline very difficult.

**Comment by sten0** [comment]
I think this one can be closed :-)

**Comment by Malabarba** [comment]
True 😁
