### ISSUE TITLE
rm-blacklist: modes still visible

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/smart-mode-line#108]
I customized the variabile adding a list of modes I do not want to see in my mode line. It results in this line of elisp:
`(rm-blacklist (quote (" company projectile undo-tree")))`
Yet the modes are still visible in my mode line. Am I doing something wrong?

**Comment by boccaperta-it** [comment]
Didn't work. None of the listed modes are hidden.

**Comment by Bruce-Connor** [comment]
Oh yes, I forgot the space at the start. I edited it now, try again.

**Comment by boccaperta-it** [comment]
Fantastic, works like a charm. Thank you very much for this nice solution, much better than my hack above.

**Comment by Bruce-Connor** [comment]
Your previous solution was perfectly valid, and not a hack at all. :-)
It only couldn't hide minor-modes whose name wasn't fixed. You need a
regexp for these "variable modes", but for all other modes a list of
strings would have been fine.

Cheers!
