### ISSUE TITLE
Still having that confirmation about the themes used

### ISSUE THREAD

**Issue by angrybakon** [Malabarba/smart-mode-line#124]
I have removed everything but smart-mode-line in my config as I was trying to determine which section was being an issue (as recommended in the README).

Turns out I still get:

```none
Loading a theme can run Lisp code.  Really load? (y or n) 
```

Followed by:

```none
Treat this theme as safe in future sessions? (y or n)
```

In the end my config looks like:

```elisp
;; Initializing package manager with Melpa (Emacs > 24)
(when (>= emacs-major-version 24)
  (require 'package)
  (package-initialize)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t))

;; Smart Mode Line (https://github.com/Malabarba/smart-mode-line)
(sml/setup)
(sml/apply-theme 'automatic)
```

```bash
angrybacon@sandman .emacs.d/ $ ll elpa/
total 0
drwxr-xr-x   4 angrybacon  staff  136 Mar 31 15:18 archives
drwxr-xr-x   7 angrybacon  staff  238 Mar 31 15:18 dash-20150311.2355
drwxr-xr-x  10 angrybacon  staff  340 Mar 31 15:19 powerline-20150319.533
drwxr-xr-x   7 angrybacon  staff  238 Mar 31 15:18 rich-minority-20150305.516
drwxr-xr-x  13 angrybacon  staff  442 Mar 31 15:18 smart-mode-line-20150312.1736
drwxr-xr-x   8 angrybacon  staff  272 Mar 31 15:19 smart-mode-line-powerline-theme-20141229.1046
```

I'm using `railwaycat/emacsmacport`'s Emacs 24.4.1 on OS X.

**Comment by Malabarba** [comment]
Hi there. Thanks for all the information. Could you tell  me what's the value of your `custom-file` variable?

**Comment by angrybakon** [comment]
```none
custom-file is a variable defined in `cus-edit.el'.
Its value is nil
```

**Comment by Malabarba** [comment]
Well the problem seems to be that Emacs isn't saving your custom variables. There should be a snippet in your init file that looks like the following.

    (custom-set-variables
     ;; custom-set-variables was added by Custom.
     ;; If you edit it by hand, you could mess it up, so be careful.
     ;; Your init file should contain only one such instance.
     ;; If there is more than one, they won't work right.

Let's forget about smart mode line for a moment. 

1. Install some other theme.
2. Load it.
3. See if the above snippet shows up in your init file.

**Comment by angrybakon** [comment]
Yeah I already tried. I get this code at the end of my init.el after I answer `y` to both prompts. But everytime it will ask anyway.

Also I'm not very familiar with elisp, does your package require those 2 custom variables at the end df the configuration file to work ? My understanding was that it was only necessary as a workaround (for not *fixing* our own setup).

Thanks for your time : j

**Comment by Malabarba** [comment]
Yes, sml needs those 2, preferably at the **top** of your config file.
But sml does offer a workaround. If you add the following to the top of your file, you should get rid of this problem `(setq sml/no-confirm-load-theme t)`

**Comment by angrybakon** [comment]
Yup, saw that part of the README, but didn't try to put them at the top. Can't test right now, can it help ?

**Comment by Malabarba** [comment]
Yes. If you add `(setq sml/no-confirm-load-theme t)` to your init file, I can guarantee sml will work just fine.

**Comment by angrybakon** [comment]
Yup, but I was talking about the custom variable code : ). Also I'm curious about why I have to use your workaround.

**Comment by Malabarba** [comment]
> Yup, but I was talking about the custom variable code : ).

Yes, having the custom variable code at the top of your init file should solve your problem as well. 

> Also I'm curious about why I have to use your workaround.

It's not clear to me. Did you remove the custom variable code? Or does it just never appear?

**Comment by angrybakon** [comment]
Sorry for the late reply.

> Did you remove the custom variable code? Or does it just never appear?

The code was correctly insterted at the end of init.el but not working as intended (even when moved to the top of the file). Issue is *fixed* with your workaround, but there still is something odd happening

Thanks for the help, nonetheless : )

**Comment by alphapapa** [comment]
I'm having this same problem.  My `custom-set-variables` sexp in my init file works fine and always has.

**Comment by Malabarba** [comment]
@angrybakon I've updated the section on the Readme to be more clear about what's the regular and what's the workaround.

@alphapapa @angrybakon If you'd like to get to the bottom of this issue. I recomment the following steps:

1. Forget about smart-mode-line for the moment. Install a different theme from Melpa, and see if the same issue happens.
2. Rename your init file, and create a new one containing only the following lines. With this init file, you should be asked about the theme only once. Does it work for you or does the issue still happen?

        (custom-set-variables
         ;; custom-set-variables was added by Custom.
         ;; If you edit it by hand, you could mess it up, so be careful.
         ;; Your init file should contain only one such instance.
         ;; If there is more than one, they won't work right.
        )
        
        ;; You may need (package-initialize) here too
        
        (load-theme 'THEME-NAME)

3. Report back here with the results of each step as well as your Emacs version.

**Comment by angrybakon** [comment]
@Malabarba I got the custom-set-variable to work. However it asked twice the confirmation and I now have:

```elisp
;; Custom variables
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("f0b0710b7e1260ead8f7808b3ee13c3bb38d45564e369cbe15fc6d312f0cd7a0"
     "3c83b3676d796422704082049fc38b6966bcad960f896669dfc21a7a37a748fa" default))))
```

Is that

**Comment by alphapapa** [comment]
@Malabarba Thanks, I finally figured out the problem.  I had `(sml/setup)` before `custom-set-variables` in my init file.  I moved it to after `custom-set-variables` and the problem went away.  I thought I had that high enough in the file after I reorganized it, but apparently not.  I guess it needs to be the first thing after `(package-initialize)`.  Thanks for all your help.

**Comment by Malabarba** [comment]
@angrybakon 

> Edit: I'm guessing, one when I call sml/setup and the second when I apply my theme with sml/apply-theme ?

Yes, you can avoid this double-apply by using `(setq sml/theme THEMENAME)` before `(sml/setup)`, instead of calling `(sml/apply-theme)`

**Comment by angrybakon** [comment]
@Malabarba Yeah I've seen that in the source comments, thanks : ).
