### ISSUE TITLE
Right alignments & projectile needs reset?

### ISSUE THREAD

**Issue by Lugoues** [Malabarba/smart-mode-line#126]
It seems that right alignments are broken? Time no longer justifies to the right, `sml/mode-width` doesn't push modes to the right.  This used to be fine.

Also, if I do not toggle projectile-mode off/on, the directory string never appears if you are in a path that matches a replacer-regexp.

Config below.
```
(progn (sml/setup)
                 (display-battery-mode 1)
		 (display-time-mode 1)
		 (setq display-time-24hr-format t
		       display-time-default-load-average nil
                       sml/shorten-modes nil
		       sml/shorten-directory t
		       sml/apply-theme 'dark
		       sml/use-projectile-p 'before-prefixes
                       sml/mode-width 'right)
                 ;;reset projectile otherwise sml integration doesn't work
                 (projectile-mode 0)
                 ;;                 (projectile-mode 1)
                 (add-to-list 'sml/replacer-regexp-list '("^~/\\.emacs\\.d/" ":emacs.d:") t)
		 (add-to-list 'sml/replacer-regexp-list '("^/sudo:.*:" ":su:") t)
                 (add-to-list 'sml/replacer-regexp-list '("^~/Documents/" ":doc:") t)
		 (add-to-list 'sml/replacer-regexp-list '("^~/Dropbox/" ":db:") t)
                 (add-to-list 'sml/replacer-regexp-list '("^~/dev/" ":dev:") t))
```

**Comment by Malabarba** [comment]
How recently did this start happening?
Would you be willing to try some previous versions of sml to find out where it started?

**Comment by Lugoues** [comment]
Ok i figured it out. If i enable rich-minority on it's own, before sml, it will cause the time to not right justify. Projectile is still an issue, but I don't think it is SML's fault.

**Comment by Malabarba** [comment]
Yes, you should not enable rich minority. sml does that for you.
The projectile thing might get fixed soon. I noticed a bug in how I implemented a recent change.
