### ISSUE TITLE
How get total lines, next to current line? 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#127]
You knew me already. I have a new question. SML gives in the left corner of the mode line, the number, where the cursor currently is. 

For example, I have a buffer of 170 lines, and I'm currently on line 87. 

So I would like to display `87/170`, instead `87`. I looked into the source code of `smart-mode-line.el`, but I haven't found the function that manages the line numbers. 

Any suggestion?

**Comment by Malabarba** [comment]
> So I would like to display 87/170, instead 87. I looked into the source code of smart-mode-line.el, but I haven't found the function that manages the line numbers.

That's because sml doesn't really handle that functionality. It's a standard feature of the mode-line. :-)

> Any suggestion? 

You can try the following, after activating sml:

   (setq-default mode-line-front-space (append mode-line-front-space '(:eval (format "/%s" (line-number-at-pos (point-max))))))

**Comment by ReneFroger** [comment]
Thanks for your reply, it's appreciated. 

I added your line: 

`   (setq-default mode-line-front-space (append mode-line-front-space '(:eval (format "/%s" (line-number-at-pos (point-max)))))` in the buffer, and evaluated it with `C-x C-e`, the SML was already activated. 

But it changes nothing. So have you tried it, and it worked with you?

**Comment by Malabarba** [comment]
Sorry, I forgot a pair of parentheses. Try this:

    (setq-default mode-line-front-space
                  (append mode-line-front-space '((:eval (format "/%s" (line-number-at-pos (point-max)))))))

**Comment by ReneFroger** [comment]
It didn't help here. Did it help you then?

**Comment by Malabarba** [comment]
Yes, the new version works for me. Try adding it after `sml/setup` in your init.el and restarting emacs.

**Comment by ReneFroger** [comment]
I tried with empty Dot-emacs config, 

except the path config where it loads the packages. 

And except the following code block: 

````
(defun enable-time ()
  (interactive)
  (setq display-time-24hr-format t)
  (setq display-time-day-and-date t)
  (display-time)
  ; Align the time to right
  (setq global-mode-string (remove 'display-time-string global-mode-string))
  (setq mode-line-end-spaces
    (list (propertize " " 'display '(space :align-to (- right 17)))
        'display-time-string))
 )   

 
(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'display-time)  
(setq display-time-24hr-format t)
(setq display-time-day-and-date t)


(defun my-set-line-numbers ()
(setq-default mode-line-front-space (append mode-line-front-space '(:eval (format "/%s" (line-number-at-pos (point-max))))))  
)

(add-hook 'after-init-hook 'my-set-line-numbers) 
```

But I'm still not seeing any `87/170` on the left corner of the mode line. I still seeing `87`?

**Comment by Malabarba** [comment]
Check the code I posted. You're missing a pair of parentheses.

**Comment by ReneFroger** [comment]
You're right. When I copy your line, and visually select the line in Emacs, to paste it in the place, sometimes the paste don't work properly. Anyway, I changed it into: 

```

(defun my-set-line-numbers ()
 (setq-default mode-line-front-space (append mode-line-front-space '((:eval (format "/%s" (line-number-at-pos (point-max)))))))
)

(add-hook 'after-init-hook 'my-set-line-numbers) 

```

Saved it, and restarted Emacs with empty emacs-config except the above, with the SML. But it's still not working? You want a video? Maybe it decipher easier?

**Comment by Malabarba** [comment]
Ok, here are a few more things you can try:

1. Run the following code, the total number of lines should show up at the start of your mode-line.

        (add-to-list 'mode-line-front-space '("" (:eval (format "%s" (line-number-at-pos (point-max))))))
2. If it doesn't work, then comment out `sml` from your init file and try again.

3. If it still doesn't work, then run the following command in your SHELL of choice (bash, sh, whatever).

        emacs -q --eval '(add-to-list (quote mode-line-front-space) (quote ("" (:eval (format "%s" (line-number-at-pos (point-max)))))))'

    This command will start a clean Emacs instance, and the total number of lines in each buffer should be displayed at the very left of the mode-line.  
    If this also doesn't work, then there's something wrong with your Emacs.

**Comment by ReneFroger** [comment]
Marlarba, thanks for your helpful reply, I appreciate it a lot. 

Number 1 worked already for me with `C-x C-e`. So I wonder why this: 

`(setq-default mode-line-front-space
              (append mode-line-front-space '((:eval (format "/%s" (line-number-at-pos (point-max)))))))` 

is not working, but this will work on my setup: 

`(add-to-list 'mode-line-front-space '("" (:eval (format "%s" (line-number-at-pos (point-max))))))`

I'm trying to learn from it. However it belongs not to the scope of this issue, I tried to make it automatically on start up with 

``` 
(add-hook 'after-init-hook 'sml/setup)
(defun myTotalNumbersinBuffer()
  (interactive)
  (add-to-list 'mode-line-front-space '("" (:eval (format "%s" (line-number-at-pos (point-max))))))   )

(add-hook 'after-init-hook 'myTotalNumbersinBuffer)   
``` 
But I didn't get the numbers on start up of Emacs instance, and I couldn't figure out why. But I solved it anyway with: 
```
(add-hook 'after-make-frame-functions
    (lambda (frame)
        (select-frame frame)
        (toggle-frame-fullscreen)
        (add-to-list 'mode-line-front-space '("" (:eval (format "%s" (line-number-at-pos (point-max))))))   
        ))
```

So in the frames of Emacs instance, I get the numbers anyway on start up. Everything is fine and well. :smile: .

You could consider this issue as closed, if you want.

**Comment by Malabarba** [comment]
Great!

**Comment by ReneFroger** [comment]
I disabled it, because when you have a file with more than 1000 lines... it makes the smooth scrolling horrendously slow. When you turn it off, it makes it fast again. 

I guess it was not the intention of this feature?

**Comment by ReneFroger** [comment]
Propably he is calculating all the lines every time when the cursor enters another line when he is going down. It makes it slow then, I guess.

**Comment by Malabarba** [comment]
Yes, that's why sml stopped providing this feature, it caused noticeable lags in large files.
You can optimize it a little by only recalculating this number as part of `after-change-functions` (which is what sml did for a while). This way you won't get lag while scrolling, but you'll still get lag while typing on large files.

**Comment by ReneFroger** [comment]
Ah, clear enough. Thanks for the awesome support!

**Comment by ramblehead** [comment]
Hello, apologies for resurrecting this long closed issue.

There is a new package to keep track of a buffer's total number of lines:
[total-lines](https://github.com/hinrik/total-lines)

It is a way quicker than `(line-number-at-pos (point-max)` approach.
Would it be possible to get back total lines functionality in sml using this package/approach?
