### ISSUE TITLE
How to move things within the mode-line

### ISSUE THREAD

**Issue by angrybakon** [Malabarba/smart-mode-line#129]
Not an bug.

Let's say I want to modify the way projectile integration is displayed.

```none
... [P/myproject] ...    -->    ... [myproject:master] ...
```

Two things that don't know how to approach:

1. How to append branch label to `sml/projectile-replacement-format` ?
1. How to make it so the branch label only gets a different color (keep "[myproject" and "]" of the same color) ? I can imagine it needs to create an other face for ”[" and "]", but I'm far from being your regular Elisp guru :/

Thanks : j

**Comment by Malabarba** [comment]
You can remove the initial `P/` by doing 

    (setq sml/projectile-replacement-format "[%s]")

Adding the branch is more complicated, you would need to define an
advice or redefine one of sml's functions.

However, have you tried turning on `vc-mode`? It is essentially a
minor-mode that displays the branch on the mode-line. It will be
displayed between the buffer name and major-mode name, and it will get
a special face (like you want).

**Comment by angrybakon** [comment]
Yup, I already made that change thanks : ).

Sorry if it was too unclear but I'm actually looking for a way to have that "[myproject:master]" thing. I already see :master, I just want to display it right after projectile indicator.

If having more faces than sml has now is too difficult too implement, how can I, instead, just display vc-mode after projectile indicator ("[myproject" + ":master]")?

**Comment by Malabarba** [comment]
Sorry, the complicated part is not having more faces. The complicated part is moving vc-mode to be right after the projectile indicator. :-)

It's not impossible, it's just quite a bit of work for a very small change.

**Comment by angrybakon** [comment]
I don't really see how I can achieve that. Thanks for the reply though : j

**Comment by Malabarba** [comment]
You could try asking on Emacs.stackexchange.com

**Comment by angrybakon** [comment]
Yup, am going to : j

**Comment by angrybakon** [comment]
Just for further reference, if anyone needs this as well: [SE post](http://emacs.stackexchange.com/questions/10648/how-to-add-branch-label-next-to-projectile-string-with-smart-mode-line).

Thanks for the edit.
