### ISSUE TITLE
solarized screenshots seem incorrect

### ISSUE THREAD

**Issue by alphapapa** [Malabarba/smart-mode-line#130]
Hi again.  :)  I'm sorry to bring up this issue again, but I just noticed commit #119 and compared the screenshots to my setup, and they don't match.  Remember issue #120?  Maybe this is related to that, but I thought I had it all fixed...

Here's what my setup currently looks like: 
![smlsolarizeddark](https://cloud.githubusercontent.com/assets/601365/7109573/26b74a2c-e166-11e4-932c-414742472a2d.png)

And here's what the screenshot in the repo looks like:
![repo](https://github.com/Malabarba/smart-mode-line/raw/1f1bdefdccac37b655af1207ab10fdc286a4f180/screenshot-solarized-dark-theme.png)

I tried running `emacs -q` and evaluating...
```elisp
(require 'package)
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
			 ("marmalade" . "http://marmalade-repo.org/packages/")
			 ("melpa" . "http://melpa.milkbox.net/packages/")))
(package-initialize)
(load-theme 'solarized-dark)
(sml/setup)
```
...but it still looks like my screenshot, not the one from the repo.

I'm confused.  Is my setup messed up, or is the screenshot?  :)

**Comment by alphapapa** [comment]
I just found https://github.com/bbatsov/solarized-emacs/commit/c4db87e8d2972b8b8111565215e108dbb799e302 which seems to indicate that the screenshot in the repo is out-of-date.  I guess you can use the one I posted here if you want.  :)

**Comment by Malabarba** [comment]
Ok. Thanks for pointing this out. I'd be glad to use your screenshot, could you just make it a little smaller in height?  Just showing the mode-line + a couple of lines should be enough.

Cheers, and thanks again

**Comment by alphapapa** [comment]
![smlsolarizedlight1](https://cloud.githubusercontent.com/assets/601365/7131637/34946ac6-e247-11e4-8e0e-35a47df70686.png)
![smlsolarizeddark1](https://cloud.githubusercontent.com/assets/601365/7131638/34a3b0f8-e247-11e4-8fd5-811365167d22.png)

Sure, here you go, one for light and one for dark.

**Comment by Malabarba** [comment]
Done! Thanks a bunch.
