### ISSUE TITLE
Just wanting to express my appreciation for SML

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#131]
Sometimes I discover small things to realize how clever Smart Mode Line actually implemented is.

For today, I discovered when I have a hidden ERC buffer and when there is a new message, I will in the right corner of SML an abbreviaton of the ERC channel, to indiciate that there is a new message. :smiley: 

Awesome... Bruce, you rocks! :+1:

**Comment by Malabarba** [comment]
Thanks a lot. It's always nice to read some kind words.
