### ISSUE TITLE
Number of times sml/theme is set on doing load-theme

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/smart-mode-line#132]
I have been constantly optimizing my init.el and I make sure I understand each message I get in the \*Messages\* buffer after emacs startup.

This one particular issue is nagging me for a long time but I did not post it earlier as it does not trigger any error.

> [sml] sml/theme set to automatic [4 times]

I get that each time I load any theme; example: `(load-theme 'darktooth t)`. 

So the question is why is `sml/theme` called 4 times during each theme change? I see the screen flickr 4 times as the sml/theme is applied 4 times. That's the only 'problem'. 

But I am curious to know if you too see/expect the same.

[Here][1] is my sml setup.

[1]: https://github.com/kaushalmodi/.emacs.d/tree/a96103dcdea5c1b144a2e4edb2794aa9f42379b8/setup-files/setup-mode-line.el#L38

I am also wondering why it always says *sml/theme set to automatic* even when I explicitly set `sml/theme` to `'dark`.

I have seen this behavior probably since emacs 24.3.

**Comment by kaushalmodi** [comment]
Debug info!

I gave a shot at debugging this:

- I eval'ed `(setq sml/-debug t)` and then `M-x sml/setup` but that did not enable the debug messages.
- When I toggled edebug off and on on `sml/apply-theme`, the debug messages got enabled.

Here's the outcome on running `(load-theme 'darktooth t)`

```
Edebug: sml/apply-theme
[smart-mode-line] Warning: `sml/hidden-modes' is obsolete, use `rm-blacklist' instead
Edebug disabled: sml/apply-theme
[sml/debug] Entering apply-theme
[sml/debug] theme is: sml/theme
[sml/debug] sml/theme is: dark
[sml] sml/theme set to automatic
[sml/debug] sml/-apply-theme-is-running is: nil
[sml/debug] sml/theme is: automatic
[sml/debug] custom-enabled-themes is: (darktooth smart-mode-line-dark smyx)
[sml/debug] custom-enabled-themes is: (darktooth smyx)
[sml/debug] sml/theme is: automatic
[sml/debug] Entering -automatically-decide-theme
[sml/debug] (sml/global-theme-support-sml-p) is: nil
[sml/debug] (face-background (quote mode-line) nil t) is: #1D2021
[sml/debug] (face-background (quote default) nil t) is: #282828
[sml/debug] sml/theme is: dark
[sml/debug] theme-name is: smart-mode-line-dark
[sml/debug] Entering apply-theme
[sml/debug] theme is: sml/theme
[sml/debug] sml/theme is: dark
[sml] sml/theme set to automatic
[sml/debug] sml/-apply-theme-is-running is: t
[sml/debug] Entering apply-theme
[sml/debug] theme is: sml/theme
[sml/debug] sml/theme is: dark
[sml] sml/theme set to automatic
[sml/debug] sml/-apply-theme-is-running is: nil
[sml/debug] sml/theme is: automatic
[sml/debug] custom-enabled-themes is: (smart-mode-line-dark darktooth smyx)
[sml/debug] custom-enabled-themes is: (darktooth smyx)
[sml/debug] sml/theme is: automatic
[sml/debug] Entering -automatically-decide-theme
[sml/debug] (sml/global-theme-support-sml-p) is: nil
[sml/debug] (face-background (quote mode-line) nil t) is: #1D2021
[sml/debug] (face-background (quote default) nil t) is: #282828
[sml/debug] sml/theme is: dark
[sml/debug] theme-name is: smart-mode-line-dark
[sml/debug] Entering apply-theme
[sml/debug] theme is: sml/theme
[sml/debug] sml/theme is: dark
[sml] sml/theme set to automatic
[sml/debug] sml/-apply-theme-is-running is: t
```

**Comment by Malabarba** [comment]
> I eval'ed (setq sml/-debug t) and then M-x sml/setup but that did not enable the debug messages. When I toggled edebug off and on on sml/apply-theme, the debug messages got enabled.

Yes. For performance reasons, the `sml/-debug` option only takes effect after the file is reevaluated.

> Here's the outcome on running (load-theme 'darktooth t)

Indeed, there seems to be some bit of logic going awry in there. It's supposed to reload the sml theme every time load-theme is called on some other theme (because otherwise the theme's mode-line colors might override sml's), but it's certainly not supposed to do that 4 times.
Could you show me your sml configuration?

**Comment by kaushalmodi** [comment]
> Could you show me your sml configuration

[my sml config](https://github.com/kaushalmodi/.emacs.d/blob/a96103dcdea5c1b144a2e4edb2794aa9f42379b8/setup-files/setup-mode-line.el#L38)

**Comment by kaushalmodi** [comment]
Looks like some sort of recursion is happening here. My load theme is causing the sml theme to be enabled after that theme is enabled. But enabling of the sml theme is causing that theme to enable again? (not sure)

I also see a problem that setting the theme to `'dark` is probably not effective; it ends up trying to figure out the theme automatically. 

```
[sml/debug] sml/theme is: dark
[sml] sml/theme set to automatic
[sml/debug] sml/-apply-theme-is-running is: nil
[sml/debug] sml/theme is: automatic
```

**Comment by Malabarba** [comment]
> I also see a problem that setting the theme to 'dark is probably not effective; it ends up trying to figure out the theme automatically.

Yes, I noticed that too. [Here is the reason](https://github.com/kaushalmodi/.emacs.d/blob/a96103dcdea5c1b144a2e4edb2794aa9f42379b8/custom_25_0.el#L106).

Remove that customization and I think everything should work as intended.

**Comment by kaushalmodi** [comment]
Thank you! Removing that from custom.el fixed it. It was **again** the pesky Customize changing stuff behind my back. I have tried setting `sml/theme` to `'automatic` when it was first introduced and must have hit Save in some Customize buffer.

But I cannot understand why that causes a problem. I load custom el first and then my custom sml setup where I setq `sml/theme` to `'dark` or `'light`.

**Comment by Malabarba** [comment]
> But I cannot understand why that causes a problem.

Whenever you call `load-theme`, all of your custom variables are reapplied. That's just how customize works. =/
In this instance, it was then `custom-set`ting the `sml/theme` variable, which causes `sml/apply-theme` to be called again.

You didn't get an infinite recursion because sml/apply-theme takes measures to prevent that.

**Comment by kaushalmodi** [comment]
Ah OK. In that case, is it safe to have sml/theme as defcustom? I cleaned up my custom el of all unintended var settings (thanks for this headsup!!). But now I will pay a close attention to sml/theme setting in there.

The issue is that Customize saves ALL the changed variables even when I hit Save for any one variable via Customize.

**Comment by kaushalmodi** [comment]
[Cleaned up my custom el's](https://github.com/kaushalmodi/.emacs.d/commit/9c72887fb1a11bfb6e29b15e48ffd8ab944083e3).. Finally! Fixed this one nagging issue I faced all this time with emacs startup and theme switching! 

Thanks! :)

**Comment by Malabarba** [comment]
> Ah OK. In that case, is it safe to have sml/theme as defcustom? 

Yes. It's safe because sml/apply-theme takes care to avoid an infinite recursion.

It would be nice to avoid so many calls to it, but that's non-trivial to do right now. Having a custom variable that controls the loading of themes (which are themselves governed by custom) is messy. =/
