### ISSUE TITLE
[feature request] Buffer indicator in SML?

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#133]
[I saw a neat feature in Spacemacs](https://github.com/syl20bnr/spacemacs/issues/1430). An indicator to give you hints where the point in the buffer currently resides. 
The relevant code to get this working is only to be applied on Powerline: 

```
(defun powerline-hud (face1 face2 &optional width)
  "Return an XPM of relative buffer location using FACE1 and FACE2 of optional WIDTH."
  (unless width (setq width 2))
  (let ((color1 (if face1 (face-background face1) "None"))
        (color2 (if face2 (face-background face2) "None"))
        (height (or powerline-height (frame-char-height)))
        pmax
        pmin
        (ws (window-start))
        (we (window-end)))
    (save-restriction
      (widen)
      (setq pmax (point-max))
      (setq pmin (point-min)))
    (pl/percent-xpm height pmax pmin we ws
                    (* (frame-char-width) width) color1 color2)))
```

When I tried to get this working, I did the following: 

    (add-hook 'after-init-hook 'sml/setup)
    (add-hook 'after-init-hook 'display-time)  
    (add-hook 'after-init-hook 'powerline-hud)

But it's not working (I see nothing yet), as I already expected. I need to give the location for HUD first on SML. Any idea how I could "place"  (I can't find another words to describe it)  the HUD on the SML. 

Any suggestion perhaps?

**Comment by Malabarba** [comment]
Try the following. I'm not completely sure it'll work, but it might (and I can't test atm).

    (push '(:eval (powerline-hud 'default 'region))
          (nthcdr 4 mode-line-format))

**Comment by Malabarba** [comment]
If it works you can change the 4 another number to move it around.

**Comment by ReneFroger** [comment]
Thanks for your reply, it didn't help either. :frowning:. 

But I'm aware it will be depending on my effort. But I'm not so good in Elisp yet to know how this could be solved, I just read the Emacs manual about Mode line, but I found no hidden hints there.

**Comment by Malabarba** [comment]
Ok, the following should work.

    (push '(" " (:eval (propertize " " 'display (powerline-hud 'highlight 'sml/global))))
          (nthcdr 10 mode-line-format))

This time I tested it ;-)

**Comment by ReneFroger** [comment]
I didn't worked either. But the filename of the buffer is also disappearing, I get only the path. 

So I get only 

`C:\foo\`

instead 

`C:\foo\bar.txt`. 


I guess it has something to do with [this issue](https://github.com/Malabarba/smart-mode-line/issues/116).

But it's not the intention that you're spent too much time on this to solve it. It's only a feature, which is nice to have. You have more important things to do, I guess. 

But I really appreciate your support on this. That's why I added you on Gratipay. :+1:

**Comment by Malabarba** [comment]
Thanks! I'm happy to help. :)

If the snippet above gave you weird results, you can try using a different number instead of 10. 

You can also try the following snippet:

    (add-to-list 'global-mode-string
                 '(" " (:eval (propertize " " 'display
                                          (powerline-hud 'highlight 'sml/global)))))
