### ISSUE TITLE
Weird values in the time-display in the SML. Not sure if related to SML. 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#134]
Sometimes I have odd numbers displayed in my time line. This is my current Mode Line configuration for the time display: 

```
(setq-default mode-line-buffer-identification
" Display the current directory, next to buffer name
              (let ((orig (car mode-line-buffer-identification)))
                `(:eval (cons (concat ,orig " " (abbreviate-file-name default-directory))
                              (cdr mode-line-buffer-identification)))))
;; -----------------------------------------------------------------------------
;; Display time in mode line 
;; -----------------------------------------------------------------------------
(defun enable-time ()
  (interactive)
  (setq display-time-24hr-format t)
  (setq display-time-day-and-date t)
  (display-time)
  ; Align the time to right
  (setq global-mode-string (remove 'display-time-string global-mode-string))
  (setq mode-line-end-spaces
    (list (propertize " " 'display '(space :align-to (- right 17)))
        'display-time-string))
 )   

 
(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'display-time)  
(setq display-time-24hr-format t)
(setq display-time-day-and-date t)
```

The time is being displayed on the right side of the mode line. 
For example, it's now `za mei 9 21:33`. It looks fine now. 

![unt11itlesssd](https://cloud.githubusercontent.com/assets/5211845/7551720/134c0926-f694-11e4-904c-4c41c766b85f.png)

But sometimes it displays weird numbers. I did nothing, I stare to the screen, and I did not anything in Emacs or on computer. A moment later, its: 

![untitled](https://cloud.githubusercontent.com/assets/5211845/7551696/8badae66-f693-11e4-9bbf-46f4c6175164.png)

Now `0.12`, right next to the time is displayed? Why? 

![unt11itled](https://cloud.githubusercontent.com/assets/5211845/7551697/8e217f7e-f693-11e4-9bec-487b7a8bf309.png)

And now `0.27` is displayed.

Might be worth to notice its often the same number that's being displayed. Always with leading zero and dot.. number number. But it will be never higher than above 
around 0.50.. 

And no, there are not another actions on Emacs/computer, when the odd numbers are being displayed. They only occur when the minute changes. 

Any suggestion?

**Comment by Malabarba** [comment]
That number you're seeing is the system load average. I don't recall right now exactly how to disable it, but I can look it up for you next time I'm at a computer.

**Comment by Malabarba** [comment]
Try the following:

    (setq display-time-default-load-average nil)

**Comment by ReneFroger** [comment]
It seems to be working now. Thanks for your support!
