### ISSUE TITLE
How change the background color of SML of inactive buffer? 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#135]
Currently my screen looks like this: 

![schermafdruk 2015-05-09 22 57 27](https://cloud.githubusercontent.com/assets/5211845/7552018/c98d6a40-f69e-11e4-92a1-efd298a518d5.png)

The black SML is the active buffer, where the pointer currently is. The grey SML is the inactive buffer. I would like to change the color of the grey. When I do a checkup in the manual of SML, I do `M-x sml/customize`. And when I check the Smart Mode Line faces, I couldn't find the variable for background color. 

Okay, then in my own written theme, I changed the values of the variable `mode-line-active` in my own written theme: 

```
   `(mode-line-inactive
     ((t (:background brown-1
                      :box (:line-width -1 :style released-button)))))
```

or 

``    ;; '(mode-line-inactive ((t :foreground "gray30" :background "#572917" )))

without any result. Any idea how to figure out where SML reads the colors of the SML? 

Thanks in advance.

**Comment by Malabarba** [comment]
Your first try was mostly correct. The right way of changing the appearance of the inactive mode-line is by changing the `mode-line-inactive`.

I think the reason why it didn't work for you is that colors have to be written as strings, like this:

    `(mode-line-inactive
      ((t (:background "brown-1"))))

See if this works for you.

**Comment by ReneFroger** [comment]
Sorry for my belated response. I just noticed your answer now.  Yes it works, your help is really appreciated!

**Comment by twashing** [comment]
Thanks guys - this helped a lot, as I'm trying to do something similar. Only this time, I want to modify the foreground font colors in the inactive buffers. Even better would be a way to lower the opacity or dim the inactive buffer fonts in somehow. I've been digging through the internet all day ([see here](http://emacs.stackexchange.com/questions/18925/setting-modeline-colors-in-other-windows)). Is there a way of doing this?

**Comment by vyp** [comment]
@twashing Wait, can't you just use `:foreground`, or am I misunderstanding?

**Comment by Malabarba** [comment]
No, I don't think that's possible. Sorry, @twashing.:-(
Because all of the sml faces already provide foregrounds,setting the foreground of `mode-line-inactive` won't work. 

You could try using other properties, like :box or :weight.

**Comment by vyp** [comment]
@Malabarba can't it be overrided though? As in, isn't that the norm?

**Comment by Malabarba** [comment]
The norm is a mode line with no faces, then the mode-line-inactive face determines every property of the  mode line for inactive buffers. 
However, as soon as you add faces on the mode line (like sml does), they take precedence over the faces mode-line and mode-line-inactive.

**Comment by vyp** [comment]
@Malabarba But couldn't one just modify (a little bit) whatever faces sml applies to the mode line?

**Comment by Malabarba** [comment]
@vip I don't think we're talking about the same thing.
Yes, you can absolutely modify the sml faces to have a different foreground. :+1: 

What I'm saying is that there's no way to have the sml faces show a different foreground depending on whether the window is active or inactive.

**Comment by vyp** [comment]
@Malabarba Ah so it was my misunderstanding. I thought there *were* different faces for active vs inactive windows. But my memory deceived me.

Is there a hook for when one switches windows? Because if there is, I think it could be done? But I can't seem to find any such hook... The thing is, I think @twashing's use case is very reasonable, and I'm surprised there isn't already a window switch hook of some sort.

**Comment by twashing** [comment]
Thanks for the feedback @Malabarba and @vyp . Remind me of the `customize` command and variable to use, to set things like `:box` and `:weight`? And what visual thing will the `:box` property affect?

**Comment by vyp** [comment]
@twashing I think either `sml/customize` or `sml/customize-faces`. @Malabarba will know for sure of course.

**Comment by twashing** [comment]
@vyp no that's not it. I need the generic emacs customize function for the `mode-line-inactive` variable.

**Comment by vyp** [comment]
@twashing oh right. I'm not sure then.

@Malabarba Of course, the `mode-line-inactive` face does exist, so there might be some window switching hook. Otherwise, I'm just not sure how it knows when to calculate if the mode line is active or not.

**Comment by Malabarba** [comment]
@twashing just issue `customize-face`, and write mode-line-inactive at the prompt. 

@vyp there might be some window switching hook. But I think the reason why mode-line-inactive works is that it is used directly by the display engine.

**Comment by twashing** [comment]
Sweet. Thanks @Malabarba.
