### ISSUE TITLE
Extend mode line over the fringe

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/smart-mode-line#136]
Hi,

I don't know if this is happening because of my recent OS upgrade (32-bit to 64-bit), but this is how the mode-line looks now:
![2015-05-31-123301_227x87_scrot](https://cloud.githubusercontent.com/assets/8199224/7901623/686e0ac2-0791-11e5-8880-f0f673ad8260.png)
Is there a way to extend it over the fringe, basically to make it look like this (from ```emacs -Q```)?
![2015-05-31-123526_170x55_scrot](https://cloud.githubusercontent.com/assets/8199224/7901628/90649456-0791-11e5-96c9-d3e2ef0da0e0.png)

Thank you.

**Comment by Malabarba** [comment]
Oh, I don't even know how to start debugging that. :)
It might be a bug in the display engine. I've been experience some weird display bugs when I (accidentally) right click an emacs buffer and then type `escape` to close the context menu that opens.

**Comment by manuel-uberti** [comment]
Ok, let's close this one this. Because I really don't have a clue either. :)

**Comment by manuel-uberti** [comment]
I found the fix, and it was not related to your awesome package. Just need to start Emacs with ```emacs -ib 0```

**Comment by Malabarba** [comment]
Great. What does that command mean?

**Comment by manuel-uberti** [comment]
It refers to an internal border on the frame, default value is ```1```. Never had this issue before, though.
