### ISSUE TITLE
Invalid face error

### ISSUE THREAD

**Issue by recifx** [Malabarba/smart-mode-line#138]
I get the following error when using `smart-mode-line` in emacs 25.0.50 on Windows 8:

```lisp
Debugger entered--Lisp error: (error "Invalid face" powerline-active2)
  internal-set-lisp-face-attribute(powerline-active2 :inherit sml/global 0)
  set-face-attribute(powerline-active2 nil :inherit sml/global)
  eval-buffer()  ; Reading at buffer position 1354
  load-theme(smart-mode-line-powerline t)
  sml/apply-theme(powerline nil :silent)
  sml/-setup-theme()
  sml/setup()
  eval-buffer(#<buffer  *load*> nil "c:/Users/RC/.emacs.d/init.el" nil t)  ; Reading at buffer position 17152
  load-with-code-conversion("c:/Users/RC/.emacs.d/init.el" "c:/Users/RC/.emacs.d/init.el" t t)
  load("c:/Users/RC/.emacs.d/init" t t)
```
My configuration:
````
(setq sml/theme 'powerline)
(setq sml/no-confirm-load-theme t)
(sml/setup)
````
Is there something I need to configure differently? Thanks.

**Comment by Malabarba** [comment]
Your configuration looks ok. Could you tell me what version of powerline you have installed?

If you do `M-x find-library RET powerline`, it should open the source file for you. Show me the first 20 or so lines in that file.

**Comment by recifx** [comment]
It was installed through melpa.

```lisp
;;; powerline.el --- fancy statusline

;; Name: Emacs Powerline
;; Author: Unknown
;; Version: 1.0
;; Keywords: statusline

;;; Commentary:

;; This package simply provides a minor mode for fancifying the status line.

;; Modified by: Jonathan Chu

;;; Code:

(require 'cl)

(defvar powerline-color1)
(defvar powerline-color2)

(setq powerline-color1 "grey22")
(setq powerline-color2 "grey40")

(set-face-attribute 'mode-line nil
                    :background "OliveDrab3"
                    :box nil)
(set-face-attribute 'mode-line-inactive nil
                    :box nil)

````

**Comment by Malabarba** [comment]
Are you sure you installed that from Melpa? 
The melpa powerline is [this one](https://github.com/milkypostman/powerline/blob/master/powerline.el) and it looks nothing like the one you have. Maybe that's an old file you have around?

**Comment by recifx** [comment]
I had tried emacs-powerline (git version) before I tried smart-mode-line and the old version of powerline.el that emacs was using was in the emacs-powerline directory. With that removed, the melpa version is being used and smart-mode-line seems to run fine. Sorry about the noise.

**Comment by Malabarba** [comment]
No problem, you're not the first to make that mistake. ;-)
