### ISSUE TITLE
can't get rid of system load average

### ISSUE THREAD

**Issue by pseudomyne** [Malabarba/smart-mode-line#139]
hi,
thank you for sml. been trying to tweak that from customize with no effect, even out of sml customize group turning "Display Time Default Load Average" to nil. any idea ?

**Comment by Malabarba** [comment]
Did you try restarting emacs after tweaking that variable?

**Comment by pseudomyne** [comment]
yes i did. i tried, as said, via M-x Customize, and within my dot file via (setq display-time-default-load-average nil). thank you for answering.

**Comment by Malabarba** [comment]
Make sure that `(setq display-time-default-load-average nil)` is placed immediately before calling `(display-time-mode)`. Does that help?

**Comment by pseudomyne** [comment]
it did. :dart: 
"l'ordre des coups bon dieu, comme aux échecs ! "
(display-time-mode) was called by my customize file. thank you :!

**Comment by Malabarba** [comment]
Great! Another satisfied customer. :-)
