### ISSUE TITLE
powerline theme - right side is off the screen

### ISSUE THREAD

**Issue by norbertklar** [Malabarba/smart-mode-line#140]
This is my problem: in the right side, something is off:
![screenshot_2015-07-06_12-59-37](https://cloud.githubusercontent.com/assets/9632419/8520921/358a42aa-23df-11e5-9aac-25878afe8cc0.png)

config
```
(setq sml/mode-width 'full)
(sml/setup)
(sml/apply-theme 'dark)
(require 'smart-mode-line-powerline-theme)
```

I'm using Ubuntu Mono font, if that's helps.

**Comment by norbertklar** [comment]
Looks like, I have to put the fonts setting before the sml setup.

**Comment by Malabarba** [comment]
Ok, firstly, here's a small suggestion. Change this part

    (sml/setup)
    (sml/apply-theme 'dark)
    (require 'smart-mode-line-powerline-theme)

To this

    (require 'smart-mode-line-powerline-theme)
    (setq sml/theme 'powerline)
    (sml/setup)


On a second note. It makes sense that applying a font before or after sml might interfere with the `'full` mode-width (that feature is a little fragile like that). However, having your font configuration before sml shouldn't prevent your fonts from applying, so it might be worth looking into that.

Thirdly, I was going to suggest you try the filler variable, but I see you've found it already. :)

**Comment by sumitsahrawat** [comment]
Hi. I'm stuck with something similar. I've noticed that `C-h v sml/mode-width RET` gives the following:

```
sml/mode-width is a variable defined in `smart-mode-line.el'.
Its value is right
Original value was full
```

Even though my `init.el` says:

```
(require 'smart-mode-line-powerline-theme)
(setq sml/no-confirm-load-theme t)
(setq sml/theme 'powerline)
(setq sml/mode-width 'full)
(sml/setup)
```

As far as fonts are concerned, I tried everything: before, after, no fonts.
