### ISSUE TITLE
Manual Install

### ISSUE THREAD

**Issue by Mike--F** [Malabarba/smart-mode-line#141]
Struggling with manual install. Can you post manual install instructions including everything needed for smart-mode line, rich-minority ,and a theme.  Feature rich-minority is NOT currently not included in the .zip file download of smart-mode line even though it's required.

**Comment by Malabarba** [comment]
You can find rich-minority here: https://github.com/Malabarba/rich-minority
All themes are included in the repo, though if you want the powerline theme you may have to copy one directory up.

**Comment by Mike--F** [comment]
Attempting to use powerline, copied it up one level as you stated.
Copied rich-minority into the smart-mode-line folder.

When I execute these lines
    (add-to-list 'load-path "~/.emacs.d/smart-mode-line/")
    (require 'rich-minority)
    (require 'smart-mode-line)
    (setq sml/theme 'powerline)
   ;tried both ways (setq sml/theme 'smart-mode-line-powerline)
    (sml/setup)

I get an error after sml/setup:
Debugger entered--Lisp error: (file-error "Cannot open load file" "powerline")
  require(powerline)
  eval-buffer()  ; Reading at buffer position 1255
  load-theme(smart-mode-line-powerline nil)
  (let ((theme-name (if (sml/theme-p sml/theme) sml/theme (intern (format "smart-mode-line-%s" sml/theme))))) nil (load-theme theme-name sml/no-confirm-load-theme))
  (progn (let ((theme-name (if (sml/theme-p sml/theme) sml/theme (intern (format "smart-mode-line-%s" sml/theme))))) nil (load-theme theme-name sml/no-confirm-load-theme)))
  (if sml/theme (progn (let ((theme-name (if (sml/theme-p sml/theme) sml/theme (intern (format "smart-mode-line-%s" sml/theme))))) nil (load-theme theme-name sml/no-confirm-load-theme))))

**Comment by Malabarba** [comment]
Ok, thanks for going through this. Sorry I forgot to mention you need powerline as well to use the powerline theme. Not sure if you need that call to `(powerline-default-theme)`, though.

Is everything working well now?

**Comment by Mike--F** [comment]
Your are correct (powerline-default-theme) was not needed. Cleaned it up a bit.
I have another small issue, will put it in a separate issue report so that it's not buried with this one.

**Comment by ReneFroger** [comment]
@Mike--F Thanks for your report. Could we consider this issue as closed?

**Comment by Malabarba** [comment]
@Mike--F By the way, if you want the arrows as separators you just need to set the `powerline-default-separator` variable. You shouldn't need to call `(powerline-default-theme)`.

**Comment by Mike--F** [comment]
Consider it closed.

Thanks
Mike
