### ISSUE TITLE
After updating SML, Emacs is bothering me at startup with apply theme for SML. 

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#144]
Hi there! In the past we had a conversation about how to apply hooks (see https://github.com/Malabarba/smart-mode-line/issues/116). 

Nothing is changed to my configuration that looks as following: 

    ;; -----------------------------------------------------------------------------
    ;; Display time in mode line 
    ;; -----------------------------------------------------------------------------
    (defun enable-time ()
      (interactive)
      (setq display-time-24hr-format t)
      (setq display-time-day-and-date t)
      (display-time)
                                            ; Align the time to right
      (setq global-mode-string (remove 'display-time-string global-mode-string))
      (setq mode-line-end-spaces
            (list (propertize " " 'display '(space :align-to (- right 17)))
                  'display-time-string))
      )   
    
    (setq display-time-default-load-average nil) 
    (add-hook 'after-init-hook 'sml/setup)
    (add-hook 'after-init-hook 'display-time)  
    (setq display-time-24hr-format t)
    (setq display-time-day-and-date t)

There is a reason why I apply add-hook. I bounded it to the hooks, or it will ask me everytime to confirm to apply the theme when I start Emacs up. This worked well for long time, until I decided to update all the packages with `package-list-packages`. Then I get bothered every time with the question If I want to apply the theme for SML. I don't know what's updated that makes my setup to break. Is there any way to prevent it?

Thanks in advance.

**Comment by Malabarba** [comment]
Add the following line somewhere

    (setq sml/no-confirm-load-theme t)

**Comment by ReneFroger** [comment]
Hooray! I'm getting rid of these irritating messages! 

Thanks!

**Comment by Malabarba** [comment]
;-) :+1:

**Comment by ReneFroger** [comment]
Sorry for bothering you again. But now I noticed that my time display is disappeared. :frowning: 

My setup for SML looks like this:

    ;; -----------------------------------------------------------------------------
    ;; Display time in mode line 
    ;; -----------------------------------------------------------------------------
    (defun enable-time ()
      (interactive)
      (setq display-time-24hr-format t)
      (setq display-time-day-and-date t)
      (display-time)
                                            ; Align the time to right
      (setq global-mode-string (remove 'display-time-string global-mode-string))
      (setq mode-line-end-spaces
            (list (propertize " " 'display '(space :align-to (- right 17)))
                  'display-time-string))
      )   
    
    (setq display-time-default-load-average nil) 
    ;; (add-hook 'after-init-hook 'sml/setup)
    (add-hook 'after-init-hook 'display-time)  
    
    (setq display-time-24hr-format t)
    (setq display-time-day-and-date t)
    (setq sml/no-confirm-load-theme t)
    (sml/setup)

Any suggestion, in order to get my date/time display back? It disappeared after the SML update.

**Comment by Malabarba** [comment]
Try starting Emacs with your `init.el` containing *only* the following code (comment out your entire init file, and paste this code in there). Does it display time correctly then?

    (package-initialize)
    (setq display-time-default-load-average nil) 
    (add-hook 'after-init-hook 'display-time) 
    (setq display-time-24hr-format t)
    (setq display-time-day-and-date t)
    (setq sml/no-confirm-load-theme t)
    (sml/setup)

If this works, then it seems some other configuration (or some other package) is interfering with `display-time` for you.

---

Unrelated, but I also noticed you're not using the `enable-time` function you defined.

**Comment by ReneFroger** [comment]
Yes, then it works. Then it's propably related to my configuration. Will dug it out. Thanks for helping me.

**Comment by ReneFroger** [comment]
Ok, now it gets complicated. I have the following keybinding in my configuration:


    (define-key evil-insert-state-map (kbd "''") (insert "\""))
    (define-key evil-insert-state-map (kbd "'") (insert "''"))

So I need to press only once or twice without pressing the shift key.

I noticed this causes to insert the characters in the scratch buffer when I start up Emacs. To solve this, I used this as workaround.

    (add-hook 'after-init-hook 'kill-whole-line)

So the characters `'` and `"` get erased in the scratch buffer. But this configuration causes the time/date display of SML to disappear. I'm not sure why the hell the kill-whole-line for buffer caused this.

**Comment by Malabarba** [comment]
That's because `(insert "''")` is telling Emacs to insert text at startup. :)

If you wanted to bind the `'` key to a function that calls `(insert "''")`, you would need to do this instead:

    (define-key evil-state-inser-map "'" (lambda () (interactive) (insert "''")))

However, for this particular case, you don't even need a function. So just replace those two lines with these ones:

    (define-key evil-insert-state-map (kbd "''") "\"")
    (define-key evil-insert-state-map (kbd "'") "''")

This has the same effect as what you were doing previously. However, I'm not sure if it worked the way you thought. You should be able to bind both `''` *and* `'`, since one is a prefix to the other. Are you sure the previous snippet worked for you?

**Comment by ReneFroger** [comment]
No, it will even makes more complicated. I had same in the past, but switched to insert mode. I have the US international layout on my keyboard. 

See also this issue: http://superuser.com/questions/346142/my-windows-keyboard-is-being-clever-with-the-quote-keys-how-can-i-stop-it

For example, when I'm pressing `'` and then space, the `'` will be then inserted. When I'm pressing `'` and then `e, then `é` will appear. When I'm replacing the two lines with yours, the `'` is not working anymore. But `''` will execute the second line. With my previous two lines, the `'` works again after you're pressing space or character. Given the fact that I'm using Emacs on various machines and I would like to keep the US internation layout on my keyboard, is there another solution? Might be sought in the relation between `kill-whole-line` and SML time display?

**Comment by Malabarba** [comment]
How about this instead?

    (define-key evil-insert-state-map (kbd "''") nil)
    (define-key evil-insert-state-map (kbd "'") nil)

**Comment by ReneFroger** [comment]
I tested it, and everything worked well. But when I'm reading your snippet, I couldn't figure out how you did solved it. Nice.. care to explain what's happening? 

And thanks for your help! It's appreciated.

**Comment by Malabarba** [comment]
When you write `(define-key evil-insert-state-map (kbd "'") (insert "''"))`, you are binding the "'" key to the **return value** of the `(insert "''")`. And the return value of the `insert` function is simply `nil`. So your original snippet:

    (define-key evil-insert-state-map (kbd "''") (insert "\""))
    (define-key evil-insert-state-map (kbd "'") (insert "''"))

is the same as this snippet

    (define-key evil-insert-state-map (kbd "''") nil)
    (define-key evil-insert-state-map (kbd "'") nil)

with the only difference being that the first version would insert unwanted text into the scratch buffer at startup.

---

I'm not 100% sure why either of these snippets solve your weird keyboard issue with the quotes key. But that's entirely dependendant on evil-mode and on what `evil-insert-state-map` does.

**Comment by ReneFroger** [comment]
Clear enough. But I don't understand how Emacs did figure out that Emacs needs to insert double quotes 2x when I'm pressing `' '` with the keybinding `(define-key evil-insert-state-map (kbd "''") nil)`.

**Comment by Malabarba** [comment]
Could it be something in your system's keyboard layout?
