### ISSUE TITLE
After update, my buffer's background changed to white!

### ISSUE THREAD

**Issue by zwb-ict** [Malabarba/smart-mode-line#146]
Before I update, my theme's background is black, after update, It seems that all my color settings are changed by sml.

emacs version: 24.5

My sml setting:
(setq powerline-arrow-shape 'curve)
(setq powerline-default-separator-dir '(right . left))
(setq sml/theme 'powerline)
(sml/setup)

**Comment by zwb-ict** [comment]
I'm sorry, I found the problem, Prelude 's UI has changed, it calls sml/setup after init, I used to call this by myself.

**Comment by Malabarba** [comment]
Indeed. Glad you've solved it. ☺
