### ISSUE TITLE
don't load fancy simbols

### ISSUE THREAD

**Issue by arkhan** [Malabarba/smart-mode-line#147]
Hello, Great work,
I'm installed smart-mode-line and smart-mode-line-powerline-theme, but when run emacs -nw in URxvt
don't load fancy symbols.

I use Terminess Powerline font in URxvt:
```
URxvt*font:                     xft:Terminess Powerline:size=9.5,xft:DejaVu Sans Mono:pixelsize=13,xft:Symbola:size=13
URxvt*boldFont:                 xft:Terminess Powerline:bold:size=9.5,xft:DejaVu Sans Mono:pixelsize=13,xft:Symbola:size=13
URxvt*italicFont:               xft:Terminess Powerline:italic:autohint=true:size=9.5,xft:DejaVu Sans Mono:pixelsize=13,xft:Symbola:size=13
URxvt*boldItalicFont:           xft:Terminess Powerline:bold:italic:autohint=true:size=9.5,xft:DejaVu Sans Mono:pixelsize=13,xft:Symbola:size=13
```
And in init.el:
 ```
(require 'smart-mode-line)
(setq sml/no-confirm-load-theme t)
(sml/setup)
(sml/apply-theme 'powerline)
```
![Emacs in URxvt](http://i.imgur.com/dsNDGN3.png)

**Comment by Malabarba** [comment]
I think emacs can only display images in a graphical frame, and the fancy powerline separators are images. This means the powerline theme probably won't work on `-nw`. 

 The other themes should work fine, though.

**Comment by Malabarba** [comment]
Did you find a solution to this?

**Comment by arkhan** [comment]
No I use dark theme
