### ISSUE TITLE
Smart-mode-line affects customization save behavior

### ISSUE THREAD

**Issue by glucas** [Malabarba/smart-mode-line#148]
When I enable smart-mode-line it somehow changes the behavior of Easy Customization. If I comment out smart-mode-line in my init file, things go back to normal; if I put it back, I see this problem again. I'm currently seeing this with an Emacs 25 snapshot and smart-mode-line 20150803.338, but I have seen it in the past with Emacs 24.4 and earlier versions of sml, before I made the connection. 

The issue is as follows: I have a number of customization settings in my `custom-file` that I keep in a git repository. I also have some settings that are machine-specific which I set during init using `customize-set-value`, which means they are set for the current session only. But when I'm using smart-mode-line, those local customizations get saved to my `custom-file` if I happen to save some unrelated change. 

For example, I can:
- Start Emacs
- `M-x customize-variable user-mail-address`
- Change the value and then choose `Save for Future Sessions`
- Quit Emacs and check my custom file. It now contains the changed mail address but also a bunch of settings with local file system paths and so on.

If I remove smart-mode-line and follow the same steps again, only the  mail address change is written out. I haven't debugged this further yet -- no idea how this could be happening.

**Comment by Malabarba** [comment]
That is strange indeed. What happens if you take the following steps **without** using smart-mode-line?

- Start Emacs
- M-x load-theme (then chose some theme to load)
- M-x customize-variable user-mail-address
- Change the value and then choose Save for Future Sessions
- Quit Emacs and check my custom file. It now contains the changed mail address but also a bunch of settings with local file system paths and so on.

**Comment by glucas** [comment]
Aha -- you nailed it, this is a side-effect of `customize-theme` rather than anything specific to `smart-mode-line`.

**Comment by glucas** [comment]
A bit more testing: Any customizations made to the current session before calling `load-theme` will get persisted when you save a customization after `load-theme`.

If I load a theme first and then make session-only customizations, things behave as expected. So the act of loading a theme changes the status of any session-local customizations.

**Comment by Malabarba** [comment]
Have you tried reproducing from Emacs -Q? 
If that works then yes, I think it's an emacs bug. 

The team might already know about it, but it's worth asking there. It could be we're doing something wrong.

**Comment by glucas** [comment]
Will do, thanks. Closing this issue since it is not an sml problem.
