### ISSUE TITLE
Pomodoro time disappear!

### ISSUE THREAD

**Issue by hello-code** [Malabarba/smart-mode-line#149]
Hi  Malabarba:
Thanks for your good job!
I use `pomodoro (20150716.1046 (melpa))` that will show time in mode line :
![po](https://cloud.githubusercontent.com/assets/7741586/9567719/1841ba8e-4f68-11e5-9f77-1be466903f79.jpg)

However, when I use `smart-mode-line` it disappeared.
![po2](https://cloud.githubusercontent.com/assets/7741586/9567795/05199542-4f6a-11e5-9450-6d8f8335ea7a.jpg)

I want to show the pomodoro time in mode line.How can I do that?
Thanks for your help!

This is my config:
```lisp
(require 'smart-mode-line)
(setq sml/no-confirm-load-theme t)
(setq sml/theme 'dark)

(sml/setup) ;; activate it
(setq sml/name-width 40)
(setq sml/mode-width "full")
(setq sml/shorten-directory t)
(setq sml/shorten-modes t)

(setq sml/mode-width 62)

;; hide minor mode https://github.com/Malabarba/smart-mode-line/issues/108
(setq rm-blacklist
      (format "^ \\(%s\\)$"
        (mapconcat #'identity
                   '("FlyC.*"
		     "Helm"
		     "yas"
                     "company"
                     "Undo-Tree")
                   "\\|")))

(deftheme smart-mode-line-dark "Dark theme for smart-mode-line.")
(custom-theme-set-faces
 'smart-mode-line-dark
 '(mode-line-inactive ((t :foreground "gray" :background "#404040" :inverse-video nil)))
 '(mode-line     ((t :foreground "gray60" :background "dark green" :inverse-video nil)))
 '(sml/global    ((t :foreground "black" :inverse-video nil)))
)
```

**Comment by Malabarba** [comment]
Thanks for filing this. The way that pomodoro sets its mode-line info is probably incompatible with what we do due to some corner case.

Could you provide a link to pomodoro's source code?

**Comment by Malabarba** [comment]
Also (unrelated) your `mode-width` should be `'full`, not `"full"`.

**Comment by hello-code** [comment]
Thanks for reply!
The pomodoro's source :https://github.com/baudtack/pomodoro.el/blob/master/pomodoro.el

**Comment by hello-code** [comment]
This is new config:
```
(require 'smart-mode-line)
(setq sml/no-confirm-load-theme t)
(setq sml/theme 'dark)

(sml/setup) ;; activate it
(setq sml/name-width 40)
(setq sml/mode-width 'full)------------>change "full" to 'full
(setq sml/shorten-directory t)
(setq sml/shorten-modes t)


;; hide minor mode https://github.com/Malabarba/smart-mode-line/issues/108
(setq rm-blacklist
      (format "^ \\(%s\\)$"
        (mapconcat #'identity
                   '("FlyC.*"
		     "Helm"
		     "yas"
                     "company"
                     "Undo-Tree")
                   "\\|")))

(deftheme smart-mode-line-dark "Dark theme for smart-mode-line.")
(custom-theme-set-faces
 'smart-mode-line-dark
 '(mode-line-inactive ((t :foreground "gray" :background "#404040" :inverse-video nil)))
 '(mode-line     ((t :foreground "gray60" :background "dark green" :inverse-video nil)))
 '(sml/global    ((t :foreground "black" :inverse-video nil)))
)

```
`system load average` disapear!
![default](https://cloud.githubusercontent.com/assets/7741586/9570920/3f2ff24a-4fc8-11e5-8cae-119875bb279c.png)

```(setq display-time-format "[%Y-%m-%d %H:%M:%S %A]")```

**Comment by hello-code** [comment]
I found it!
Change the order will fix `pomodoro disapear`,
```
(require 'init-smart-mode-line)
(require 'init-pomodoro);not org-pomodoro
```

But `system load average` still can not see!

**Comment by Malabarba** [comment]
The mode-width `full` option can get confused with the system load-average. Try setting `sml/mode-width` to a number, like `20` or something.

**Comment by hello-code** [comment]
Thanks!
Thank you very much!

**Comment by Malabarba** [comment]
So it's all working now?

**Comment by hello-code** [comment]
Yes!All working now.
Thank you !

**Comment by Malabarba** [comment]
Great! Happy to help.
