### ISSUE TITLE
Magit 2.x is dramatically slower with smart-mode-line enabled

### ISSUE THREAD

**Issue by nshi** [Malabarba/smart-mode-line#151]
Not sure if this appears on other systems, I'm using Mac OS X Yosemite. When sml is enabled, magit status view takes significantly longer time to refresh.

The following issue describes this in detail.

https://github.com/magit/magit/issues/2228

**Comment by Malabarba** [comment]
Could you try using the profiler? M-x profiler-start and then M-x profiler-report.

**Comment by ReneFroger** [comment]
@nshi , any update on this?

**Comment by nshi** [comment]
Sorry for the lack of response. I turned sml off after I created the issue and turned it back on to get the profile @Malabarba asked for, but the problem was gone. I've been using sml and magit for a bit more than a week without any noticeable slowdown now. Very weird.

**Comment by ReneFroger** [comment]
@nshi, it would be nice if you close this issue then. :)

**Comment by Malabarba** [comment]
Glad to know it's resolved, then. :+1:

**Comment by nshi** [comment]
Thanks for closing it, @Malabarba. I should've done it when the problem disappeared.
