### ISSUE TITLE
Smart Mode Line with the newest development version of Emacs

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#153]
## Setup:
GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-10-05
[Compiled from EmacsW64.](http://emacsbinw64.sourceforge.net/)

Smart Mode Line, using the latest version of Smart Mode Line from MELPA

Windows 7 x64 bit.

## Situation:

I use the time-display feature in Smart Mode Line. See also this issue: https://github.com/Malabarba/smart-mode-line/issues/116

When using GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32), compiled on the date 2015-07-25 on KAEL for Windows (see http://sourceforge.net/projects/emacsbinw64/files/snapshot/), the Smart Mode Line appears as following:

![desktop111](https://cloud.githubusercontent.com/assets/5211845/10576992/cd0f97ee-7667-11e5-88ac-a7e829bb3372.png)

And with the newest compilation of Emacs, GUI version GNU Emacs 25.0.50.1 (x86_64-w64-mingw32), compiled on 2015-10-05, the date/time display on Smart Mode Line appears as following:

![untitled](https://cloud.githubusercontent.com/assets/5211845/10576738/ef9765be-7665-11e5-81c0-070175ef0fd1.png)

So I'm not sure if this is related to Smart Mode Line, or it could be considered as a bug in graphical renderer of Emacs.

**Comment by Malabarba** [comment]
It looks like some sort of locale issue.

In the first pic Emacs uses some other language to display the time.
In the second pic it's displayed as english.

That's probably unrelated to sml. Try starting `emacs -Q` and then invoking `M-x display-time-mode`. What do you see?

**Comment by ReneFroger** [comment]
When starting  `emacs -Q` and then calling <kbd>M-x display-time-mode</kbd> in the newest version of Emacs (compiled on 2015-10-05), I see the message "`Display-Time mode enabled`" in the minibuffer.

**Comment by Malabarba** [comment]
Probably just a momentary issue then. Was that the only problem?

**Comment by ReneFroger** [comment]
No, the date/time display is still of the modeline.

**Comment by Malabarba** [comment]
Ah wait. I think I misunderstood your problem. So your issue is that the display is going beyond the edge of the window?

**Comment by Malabarba** [comment]
I see there's a character in your mode-line that isn't being displayed correctly. That's probably why the width is off.

**Comment by ReneFroger** [comment]
Yes, it's beacon mode (latest minor mode in the second screenshot). When disabling it, the display of date/time is not beyond the edge of the window anymore. :+1: 

But I see it now, in the old version of Emacs, compiled on 2015-07-25 on KAEL, beacon is displayed as /\. But  in the newest version of Emacs the Beacon mode is not  displayed correctly. 

I never thought the list of minor modes could push the date/time display off the edge. 
I don't think it should be an issue, given the fact this is a development version of Emacs and not the official version.

Thanks for your help!
