### ISSUE TITLE
Can't get rm-excluded-modes to work

### ISSUE THREAD

**Issue by aiguofer** [Malabarba/smart-mode-line#154]
I'm trying to exclude Helm and Wrap from minor mode list but I can't seem to be able to.

I've tried the following:
```
(add-to-list 'rm-excluded-modes "Helm")
(add-to-list 'rm-excluded-modes "Wrap")
(add-to-list 'rm-excluded-modes " Helm")
(add-to-list 'rm-excluded-modes " Wrap")
(add-to-list 'rm-excluded-modes "helm")
(add-to-list 'rm-excluded-modes "wrap")
(add-to-list 'rm-excluded-modes " helm")
(add-to-list 'rm-excluded-modes " wrap")
```
and nothing seems to work. What am I doing wrong?

**Comment by Malabarba** [comment]
`(add-to-list 'rm-excluded-modes " Helm")` should have worked. What's the value of `rm-excluded-modes` for you after you execute that.
Also, could you show your other configurations related to sml or rich-minority?

**Comment by aiguofer** [comment]
after add-to-list for both wrap and helm I have `(" Wrap" " Helm" " hl-p")`

here's the relevant config
```
(custom-set-variables
 '(sml/theme (quote dark)))

(add-hook 'after-init-hook 'sml/setup)
(add-hook 'after-init-hook 'powerline-default-theme)

(add-to-list 'rm-excluded-modes " Helm")
(add-to-list 'rm-excluded-modes " Wrap")
```

**Comment by Malabarba** [comment]
That's the issue.
Remove that call to `powerline-default-theme`. It's interfering with smart-mode-line. ;-)

**Comment by aiguofer** [comment]
ahhh.... that sucks :( I really like the powerline-default-theme (I tried smart-line-mode-powerline but it didn't work very well for me). The sml path stuff seems to work just fine, but I guess powerline takes over the minor mode section.

Thanks!
