### ISSUE TITLE
can't load smart-mode-line at startup

### ISSUE THREAD

**Issue by akater** [Malabarba/smart-mode-line#159]
Following this emacs.stackexchange answer: https://emacs.stackexchange.com/a/306, I
* installed smart-mode-line and powerline theme
* tested it; everything went fine
* added `(sml/setup)` to my `~/.emacs`
* got “Symbol's function definition is void: sml/setup” error on startup
* added `(require 'smart-mode-line)` to `~/.emacs`
* got “File error: Cannot open load file, no such file or directory, smart-mode-line” on startup

Nevertheless, I can successfully run `(sml/setup)` once Emacs starts, right after that.

Granted, it is not necessarily a smart-mode-line issue. I'm not an experienced Emacs user and could well mess up general setup somewhere. Still, I have quite a lot `require` expressions in my `~/.emacs`, and this is the only one causing this so far. `load-path` list does contain the smart-mode-line directory.

**Comment by Malabarba** [comment]
Indeed, it's not a smart-mode-line issue. :wink: 
Try this other question: https://emacs.stackexchange.com/questions/5828/why-do-i-have-to-add-each-package-to-load-path-or-problem-with-require-packag

**Comment by akater** [comment]
Thank you. I did search for a more direct explanation but unsuccessfully. :-(

**Comment by Malabarba** [comment]
No problem. Happy to help.
