### ISSUE TITLE
smart-mode-line-powerline-theme w/ UTF-8 support?

### ISSUE THREAD

**Issue by dongcarl** [Malabarba/smart-mode-line#161]
I was wondering if https://github.com/Malabarba/smart-mode-line/blob/master/themes/smart-mode-line-powerline-theme.el had UTF-8 support at all? I tried setting powerline-default-separator to utf8 and the utf codes for powerline-utf-8-separator-* to the right values but I don't seem to be able to get them to show up on my terminal. (I run iTerm w/ UTF-8 enabled and the powerline font chosen)

**Comment by Malabarba** [comment]
1. Does it work if you set other values for `powerline-default-separator`? (this is to figure out whether the problem is really with utf8, or if this variable just isn't working for you)
2. If you insert these utf8 characters in some buffer, do they display correctly for you?

**Comment by dongcarl** [comment]
@Malabarba 1. No it still doesn't work 2. Typing out the characters in a buffer works... Could it be that I'm using the wrong unicode integer? I'm using 831 for the right pointing one and 833 for the left pointing one, are those correct?

**Comment by Malabarba** [comment]
Maybe. Let me see your configuration.

**Comment by dongcarl** [comment]
@Malabarba here you go: https://gist.github.com/dongcarl/b529167c76ba3d6f92cb

**Comment by dongcarl** [comment]
@Malabarba I found the correct integers... It's 57520 for left and 57522 for right. Hope someone finds this useful

**Comment by Malabarba** [comment]
Great. Glad it's solved.
