### ISSUE TITLE
incorrect buffer name on startup

### ISSUE THREAD

**Issue by lyro** [Malabarba/smart-mode-line#166]
For some reason the display of the buffer-name is wrong when starting a fresh Emacs (with smart-line-mode, of course ;)). Although I've set the variable `sml/show-file-name` to nil, the complete path of a visited file is shown.

I can update the modeline by calling `(sml/generate-buffer-identification)`. After that everything works as expected.

I suggest to call `(sml/generate-buffer-identification)` at least once in `(sml/setup)` (should be no problem because this function is typically called only once).

Furthermore, when customizing the variable `sml/show-file-name` by `M-x customize-variable RET sml/show-file-name RET` and so on, the effect is not shown immediately. I thinkg the problem is the same: `(sml/generate-buffer-identification)` is never called. Maybe changing the customization variable should trigger that function, too? (maybe do the same for other variables?)

**Comment by Malabarba** [comment]
This is odd. `sml/show-file-name` is not suppose to affect how the path is displayed. It only affects whether to use the buffer name or the file name *at the end of the path*.

sml doesn't have an explicit option for hiding the path. Although you can get a similar effect by setting `(setq sml/name-width 0)`.

**Comment by lyro** [comment]
I see. Actually I remembered that the problem was slightly different. Maybe it was some interaction with projectile or so. Anyway, it seems not to be important anymore, so sorry for the noise.
