### ISSUE TITLE
Adding ELPA to the replacer-alist

### ISSUE THREAD

**Issue by cpitclaudel** [Malabarba/smart-mode-line#170]
Hi Artur,

What would you think of adding something like this to the replacer alist?

```
("^~/\\.emacs\\.d/elpa/" ":ELPA:")
```

The advantage is that it gives me a quick way to check if I'm looking at sources installed through (M)ELPA.

Something similar could be nice for

```
 ("^~/\\.emacs\\.d/lisp/" ":LISP:")
```

What do you think?

**Comment by Malabarba** [comment]
The first one sounds great. I think the second is better reserved for user customizations.

**Comment by cpitclaudel** [comment]
Great; I made a PR.

**Comment by cpitclaudel** [comment]
Great; I made a PR.
