### ISSUE TITLE
Disable border of smart-mode-line

### ISSUE THREAD

**Issue by zxcvbn97** [Malabarba/smart-mode-line#173]
Hi there,

Is there anyway to disable the border of smart-mode-line. The border is the gray line under the smart modeline in the attached image. Thanks!
![image](https://cloud.githubusercontent.com/assets/9757976/12768763/a579cf7e-c9d7-11e5-84dc-66c2196537f5.png)

**Comment by Malabarba** [comment]
The default sml themes don't have that line. It's probably coming from your global theme.
