### ISSUE TITLE
sml/show-remote: don't show a dash on local files?

### ISSUE THREAD

**Issue by fice-t** [Malabarba/smart-mode-line#174]
Could there be a configuration option so that having `sml/show-remote` on doesn't prepend a `-` to the buffer name in local files? Currently the doc-string for it says:

`Whether to show an "@" for remote buffers.`

I'd like it to just do that.

**Comment by Malabarba** [comment]
It's possible, but I think it would add some reasonable complexity to the code for very little benefit (Meanwhile, the current behaviour takes 2 lines to implement).

On the bright side, I've extended the docstring to clarify what actually happens. :-)
