### ISSUE TITLE
Symbol's function definition is void: powerline-current-separator

### ISSUE THREAD

**Issue by maxmurdoch** [Malabarba/smart-mode-line#175]
I get the above error when trying to initialize sml using `sml/setup`. Presumably related to https://github.com/Malabarba/smart-mode-line/commit/9a69b43365cb86e95445c1545a6ebfb13d96d2cf

Thanks in advance for taking time to help with this, and keep up the rad work :smile:

**Comment by maxmurdoch** [comment]
Turns out the `smart-mode-line-powerline-theme` package had been marked as redundant and removed.

**Comment by maxmurdoch** [comment]
I thought the above had fixed it. Alas, not so easy. I tried reinstalling `smart-mode-line-powerline-theme`. After doing that `sml/setup` freezes.

**Comment by Malabarba** [comment]
Does it freeze if you call that manually?

**Comment by maxmurdoch** [comment]
No. If I call it manually I get the error I mentioned in the description: Symbol's function definition is void: powerline-current-separator. If it helps, I have `(prefer-coding-system 'utf-8)`.

**Comment by Malabarba** [comment]
Could you open the packages menu and check if powerline is installed?

**Comment by maxmurdoch** [comment]
It's installed as a dependency. I just tried manually installing it and the same `Symbol's function definition is void` error was thrown.

**Comment by Malabarba** [comment]
Hm. I just gave it a try and experienced a hang too. My guess is that the powerline theme changed in some incompatible way. I'll have to investigate.

**Comment by maxmurdoch** [comment]
Thanks for taking the time @Malabarba! :smile:

**Comment by Malabarba** [comment]
What version of Emacs are you using? I think this might be an Emacs bug.

**Comment by maxmurdoch** [comment]
25.0.92

**Comment by Malabarba** [comment]
Have you configured any `rm-text-properties` by any chance?
I managed to track down my hang to this form:

```
(add-to-list 'rm-text-properties
             '("\\` (\\*)\\'" 'display " 💡"))
```

**Comment by maxmurdoch** [comment]
Sadly, I haven't. Did you track that down through a process of trial and error?

**Comment by maxmurdoch** [comment]
I've just found that it works if I select a powerline theme (`powerline-default-theme` for example), then call `powerline-revert`, then call `sml/setup`, but the powerline separators are chinese symbols.

**Comment by Malabarba** [comment]
What do you mean by "select a powerline theme"? 
Are you activating powerline?

**Comment by glucas** [comment]
I was hitting this error. In my case I seem to have fixed it by installing the latest version of powerline rather than the 2.2 version that was getting picked up from melpa-stable.

**Comment by azzamsa** [comment]
I try to figure it out this problem from yesterday, I think I am the only one who get this error. fortunately I find this issue.

this is my output `Error (use-package): smart-mode-line :init: Symbol's function definition is void: powerline-current-separator
Error (use-package): smart-mode-line :init: Symbol's function definition is void: powerline-current-separator
`

**Comment by Malabarba** [comment]
It looks like you might be trying to use the powerline theme for smart-mode-line, without having powerline installed. Is that the case?

**Comment by azzamsa** [comment]
i cant figure it out, how to solve this. I still having this issue.
no, i have installed 

`  smart-mode-line    2.10.1       installed             A color coded smart mode-line.`
 ` smart-mode-line... 20160705.... installed             smart-mode-line theme that mimics the powerline appearance.
`

**Comment by falematte** [comment]
I am getting the same error on emacs 25

**Comment by humitos** [comment]
I'm experimenting the same error.

I wasn't able to use `smart-mode-line` with `respectful` theme _without_ powerline.

This my configuration. I'm using `master` branch of this module.

```lisp
;; https://github.com/Malabarba/smart-mode-line
(setq sml/theme 'respectful)
(setq sml/no-confirm-load-theme t)
(setq rm-blacklist
      (format "^ \\(%s\\)$"
              (mapconcat #'identity
                         '("Fly.*"
                           "Projectile.*"
                           "PgLn"
                           "Helm"
                           "hl-s"
                           "Golden"
                           "snipe"
                           "Elpy"
                           "ctagsU"
                           "GG"
                           "Hi"
                           "Spnxd"
                           "WSC"
                           "ws"
                           "SP"
                           "DS"
                           "ARev")
                         "\\|")))

(require 'smart-mode-line)
(sml/setup)
```

If I remove everything related to `powerline` (`powerline.el`, `powerline-separators.el`, `smart-mode-line-*powerline*.el`, etc) I see first this message in the bottom of the screen saying that a function is not defined:

![captura de pantalla_2018-03-23_20-44-22](https://user-images.githubusercontent.com/244656/37859000-0d351d52-2edb-11e8-8ee6-101867e6855d.png)

and finally I get the mode line as I want:

![captura de pantalla_2018-03-23_20-42-16](https://user-images.githubusercontent.com/244656/37859004-2a5ca742-2edb-11e8-8a7f-fde03d877280.png)

but so many messages are printed in the `*Messages*` buffer while I move the cursor that finally emacs is closed with a "core dump" :/

```
Error during redisplay: (eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" (powerline-current-separator) (car powerline-default-separator-dir))) (quote sml/global) (quote powerline-active1)))) signaled (void-function powerline-current-separator)
Invalid face reference: powerline-active1
Error during redisplay: (eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" (powerline-current-separator) (car powerline-default-separator-dir))) (quote sml/global) (quote powerline-active1)))) signaled (void-function powerline-current-separator)
Error during redisplay: (eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" (powerline-current-separator) (cdr powerline-default-separator-dir))) (quote powerline-active2) (quote powerline-active1)))) signaled (void-function powerline-current-separator)
Error during redisplay: (eval (propertize " " (quote display) (funcall (intern (format "powerline-%s-%s" (powerline-current-separator) (cdr powerline-default-separator-dir))) (quote powerline-active1) (quote sml/global)))) signaled (void-function powerline-current-separator)
```

Emacs crashes like this:

```
~ ⌚ 20:44:07
$ emacs --debug-init
Fatal error 6: Aborted
Backtrace:
emacs[0xemacs[0x4ef00c]
emacs[0x509184]
emacs[0x460916]
emacs[0x463bae]
emacs[0x562aef]
emacs[0x4515cd]
emacs[0x4f89ff]
emacs[0x5a76e1]
emacs[0x41ee14]
emacs[0x4fb289]
emacs[0x4fc0f0]
emacs[0x4fdb94]
emacs[0x562a63]
emacs[0x4ef435]
emacs[0x5629e2]
emacs[0x4ef3cd]
emacs[0x4f3dbc]
emacs[0x4f40ec]
emacs[0x41496c]
/usr/lib/libc.so.6(__libc_start_main+0xea)[0x7f302c769f4a]
emacs[0x41550a]
[1]    5035 abort (core dumped)  emacs --debug-init
```

----

If I leave `powerline.el`, `powerline-separators.el` and `powerline-themes.el` (I'm using `master` from https://github.com/milkypostman/powerline) I see my mode line like this (mixed of respectful and powerline)

![captura de pantalla_2018-03-23_20-38-03](https://user-images.githubusercontent.com/244656/37858946-6d351a32-2eda-11e8-8931-eb74b70b65ae.png)

Note the powerline separators.

I'm using

```
$ emacs --version
GNU Emacs 25.3.1
```

----

I don't understand what I'm doing wrong or why I can't use `smart-mode-line` _without_ `powerline` installed --it doesn't seem to be a dependency of this module.

In case you want to see/check/debug/take a look at all my emacs configuration it's here, https://github.com/humitos/emacs-configuration

Is there anything else that I can provide to help you to debug this? I didn't find the _why_ yet and I'm confused :/

**Comment by humitos** [comment]
Just in case, I just compile `master` branch of emacs and the problem persists:

```
$ emacs --version
GNU Emacs 27.0.50
```

**Comment by Malabarba** [comment]
Try looking into your custom-settings. Do you see any mention of powerline in there? It's possible emacs accidentally saved powerline to your sml custom settings and so it's getting automatically activated.

**Comment by humitos** [comment]
@Malabarba thanks for your help.

Effectively, I had some powerline definitions in my `custom-set(faces/variables)`. I never wrote those ones there, but I suppose that when I was testing the powerline integration I say "Yes" to some question and it was saved there.

It works excellent now and I don't have that problem anymore.

Thank you so much. Appreciated.

**Comment by Malabarba** [comment]
No problem!
