### ISSUE TITLE
Integrating buffer-size notification in SML

### ISSUE THREAD

**Issue by ReneFroger** [Malabarba/smart-mode-line#178]
I use Emacs 25.05 on Xubuntu 16.04. My smart mode line is configured as followed

    (use-package smart-mode-line
        :ensure t 
        :config
        (setq display-time-default-load-average nil)

        (setq-default mode-line-buffer-identification
                        (let ((orig (car mode-line-buffer-identification)))
                        `(:eval (cons (concat ,orig " " (abbreviate-file-name default-directory))
                                        (cdr mode-line-buffer-identification)))))
        ;; -----------------------------------------------------------------------------
        ;; Display time in mode line 
        ;; -----------------------------------------------------------------------------
        (defun enable-time ()
            (interactive)
            (setq display-time-24hr-format t)
            (setq display-time-day-and-date t)
            (display-time)
            ;; Align the time to right
            (setq global-mode-string (remove 'display-time-string global-mode-string))
            (setq mode-line-end-spaces
                (list (propertize " " 'display '(space :align-to (- right 17)))
                        'display-time-string))
            )   
        (setq display-time-default-load-average nil) 
        (add-hook 'after-init-hook 'display-time) 
        (setq display-time-24hr-format t)
        (setq display-time-day-and-date t)
        (setq sml/no-confirm-load-theme t)
        (setq sml/name-width 60)
        (sml/setup)
    )

I found another cool snippet that I could use to integrate it in my SML-mode line, it displays the buffer size:

    (defun mu-get-buffer-size ()
        "Get a fancier version of `buffer-size'."
        (cond
        ((> (buffer-size) 1000000)
        (format "%7.1fM" (/ (buffer-size) 1000000.0)))
        ((> (buffer-size) 1000)
        (format "%7.1fk" (/ (buffer-size) 1000.0)))
        (t (format "%8d" (buffer-size)))))

    (setq-default mode-line-end-spaces
                    (append mode-line-end-spaces
                    '(:eval (mu-get-buffer-size))))

What am I trying here in this issue section, you might wonder? I tried to integrate it with my SML, on the same way as `enable-time` function, but it didn't worked out for `buffer-size` and I couldn't get it figured out where I went wrong. Any ideas?

**Comment by Malabarba** [comment]
Instead of `'(:eval (mu-get-buffer-size))`,  use `'((:eval (mu-get-buffer-size)))`.  Note the extra pair of parentheses. 

However, you may also want to just use "%I" instead.

**Comment by ReneFroger** [comment]
Thanks for your reply. Instead copying the answer, I would like to understand why, so I'm able to create my own Emacs Lisp later. Why is there a next pair of parentheses needed, before the literal quote? I thought you just need an extra pair of parentheses for the `let` function?

**Comment by ReneFroger** [comment]
Any update on this?

**Comment by Malabarba** [comment]
Sorry, I didn't forget about this. You're still in my inbox. :-)
I've just been overly busy with work and an upcoming cider release.

**Comment by Malabarba** [comment]
> Why is there a next pair of parentheses needed, before the literal quote? 

If you already had something in `mode-line-end-spaces`, the previous version would have an unexpected effect.

Say the variable's value was `("something")`. When you append `(:eval (mu-get-buffer-size))`, the value will be `("something" :eval (mu-get-buffer-size))`, which is wrong.
If the previous value of `mode-line-end-spaces` was nil (as is probably the case for you) then it doesn't matter.

> And I don't see any change in my mode line, after applying your recommendation:

That's strange. The following works fine for me:

    (setq-default mode-line-end-spaces
                  (append mode-line-end-spaces '("%I")))

**Comment by ReneFroger** [comment]
Thanks for your reply. Except for me propably. I really appreciate your explaining and support, it's a pleasant surprise for me to learn that you can prevent unbalanced parentheses in Elisp when you append something. 

This  is my full configuration for smart mode line: http://pastebin.com/EXZsUZSz

Perhaps you could spot where I went wrong in my configuration?

**Comment by Malabarba** [comment]
On line 36 you override the value of mode-line-end-spaces.

**Comment by ReneFroger** [comment]
You're damn right! Sorry for the inconvience. I changed it, and restarted my Emacs. But unfortunately, without seeing any change in the SML. This is my adjusted code: http://pastebin.com/bSGd9T0r

I scanned my code again to be sure that I wasn't overlooking something. Are you sure my configuration is working for you, including displaying the buffer file size?

**Comment by Malabarba** [comment]
Are you sure? The link you posted still overrides the variable on line 21:

    (setq mode-line-end-spaces
          (list (propertize " " 'display '(space :align-to (- right 17)))
                'display-time-string))

**Comment by ReneFroger** [comment]
Yes? I replaced it to up, on line 21, and then the `mode-line-end-spaces` gets his value. Then 
I append it on line 41 with adding an extra value to it. Sounds logic to me, given your previous explaination?

Or am I wrong here?

**Comment by Malabarba** [comment]
The code in line 21 is inside a function that gets added to a hook. Since the function ends up running **after** the code in line 41, it's going to override the default value.

**Comment by ReneFroger** [comment]
The code in line 21 is indeed inside the function `enable-time`. And it's not added to a hook, but `display-time` is added to a hook, I noticed it now. That means the line 21 is never run at all?

**Comment by Malabarba** [comment]
>  but I never understand how the hell enable-time gets running inside my configuration, because I see it's not being called.

Maybe it isn't. Comment out this function and restart Emacs. If the function is being called anywhere, you'll get an error.

**Comment by ReneFroger** [comment]
I commented the function `enable-time` out, and restarted Emacs. 

I don't get any error, and I still see the time being displayed in my mode line. So that function is useless. And more important, how is this related to the buffer size indicator?

**Comment by Malabarba** [comment]
After doing all that, do `C-h v mode-line-end-spaces`. What does it say about the value?

**Comment by ReneFroger** [comment]
`C-h v mode-line-end-spaces` gives me the following:

    mode-line-end-spaces’s value is ((:eval ("%I")))

**Comment by Malabarba** [comment]
Then that's the problem. It should be just `(("%I"))` or maybe  `("%I")`, but that `:eval` definitely shouldn't be in there.

**Comment by ReneFroger** [comment]
I had the same in my configuration:

     (setq-default mode-line-end-spaces
                (append mode-line-end-spaces
                        '((:eval ("%I")))))

As in the content of the pastebin link.

When changing it to the value you proposed earlier to:

  (setq-default mode-line-end-spaces
                (append mode-line-end-spaces '("%I")))

Then I see the buffer file size in my SML, but it's right next to the time display where I expected the time display to be displayed at the furthmost right. But it's working, and that's counts in this issue.

Malabarba, thanks for your help! Your support and enormous contributions to the Emacs community is always appreciated, however not everyone speaks that loudly as I do. Thanks for that!

**Comment by Malabarba** [comment]
Always happy to help. :-)
I'm sure you can get the ordering correct if you tweak it around a little bit.
