### ISSUE TITLE
misc-info color is weird

### ISSUE THREAD

**Issue by gujiaxi** [Malabarba/smart-mode-line#184]
![img](http://i.imgur.com/Y6r2tcg.png)

It seems that the *blue* (i.e. `mode-line-misc-info`) is fixed but actually it is sort of weird or even ugly. Below is the screenshot shown as a demo of this project. How can I customize it or is it a bug?

![](https://camo.githubusercontent.com/a79c5f9e824ec0fbf0736088d646d46b3e037417/68747470733a2f2f7261772e6769746875622e636f6d2f4d616c6162617262612f736d6172742d6d6f64652d6c696e652f6d61737465722f73637265656e73686f742d706f7765726c696e652d7468656d652e706e67)

**Comment by Malabarba** [comment]
Sml doesn't define a misc-info face. Is it possible that blue color is being specified by jabber?
If that's the case, you should customize the relevant jabber face.
