### ISSUE TITLE
Optional line-width customization?

### ISSUE THREAD

**Issue by jojojames** [Malabarba/smart-mode-line#185]
Is there a way to customize line-width with SML?

  (defun do-additional-theme-changes ()
    "Execute additional theme changes."
    (let* ((daytime (is-daytime))
           (mode-line-active (if daytime "#091f2e" "#eee8d5"))
           (mode-line-inactive (if daytime "#11151c" "#eee8d5")))
      (set-face-attribute 'mode-line nil
                          :box `(:line-width 2 :color ,mode-line-active))
      (set-face-attribute 'modeline-inactive nil
                          :box `(:line-width 2 :color ,mode-line-inactive))))

Doing something like this in the meantime to modify the modeline height.

**Comment by Malabarba** [comment]
sml doesn't have anything special for configuring that, but I'm pretty sure you can do it directly in Emacs. Try customizing the `mode-line` face and changing the `Line Height`.

**Comment by jojojames** [comment]
Yeah, that's how I'm currently doing it (The above does what I want but the colors are hardcoded). The problem is that the respectful modeline style doesn't color the additional padding given when changing line-width.

**Comment by Malabarba** [comment]
No. You're adding a box and giving it a specific line-width. Try customizing the line-**height**.

**Comment by jojojames** [comment]
Do you mean something like this?

      (set-face-attribute 'mode-line nil
                          :box `(:line-height 2))
      (set-face-attribute 'modeline-inactive nil
                          :box `(:line-height 2))
That gives me the same problem I described above.

Or maybe this.
      (set-face-attribute 'mode-line nil :height 2) ;; doesn't accomplish goal

**Comment by Malabarba** [comment]
Yes, I meant :height. Try `M-x customize-face RET mode-line`. Click on `show all attributes` and change the `Height` value from `1.0` to `2.0`.

**Comment by jojojames** [comment]
I believe that scales the modeline so the font becomes a little stretched too. I think the box preserves font size.
