### ISSUE TITLE
small color bug after update

### ISSUE THREAD

**Issue by umkiwon** [Malabarba/smart-mode-line#186]
Hello,

after the recent update through melpa, it seems have a bug. My test is as follows:
> emacs -Q
(require 'package)
(package-initialize)
(require 'smart-mode-line)
(custom-set-variables
   '(sml/theme 'light-powerline)
   '(sml/line-number-format "%4lL")
   '(sml/col-number-format "%3cC")
   '(sml/show-client t))
(sml/setup)

As you can see in the attached figure, the first triangle has wrong color.

![color_bug](https://cloud.githubusercontent.com/assets/6857817/15750554/36dbfc3a-28e7-11e6-880d-fc13a1d85f11.png)

**Comment by Malabarba** [comment]
Sorry for the delay. Should be fixed now.
