### ISSUE TITLE
Projectile info color is not set

### ISSUE THREAD

**Issue by swarnendubiswas** [Malabarba/smart-mode-line#188]
Hi,

With my setup, the green font face for `projectile` information is not set with `sml`. This is what I mean:

![screenshot from 2016-06-19 18-33-17](https://cloud.githubusercontent.com/assets/7343807/16180215/0059a00e-364d-11e6-95fe-c72d2b12865e.png)

For the `Projectile ~` information, shouldn't the font face be set to `DarkGreen`, which is the face for `sml/projectile`, and `sml/git` and `sml/read-only`? This does not happen as in above the screen shot. Here is a sample snippet with which I can reproduce the problem on Emacs 25.1.

```
(require 'package)
(setq package-user-dir (expand-file-name "~/.emacs.d/elpa/")
      package-enable-at-startup nil)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)

(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(eval-when-compile
  (require 'use-package))

(use-package projectile
  :ensure t
  :init (projectile-global-mode 1))

(use-package smart-mode-line
  :ensure t
  :config (sml/setup))
```

**Comment by Malabarba** [comment]
> For the Projectile ~ information, shouldn't the font face be set to DarkGreen, which is the face for sml/projectile, and sml/git and sml/read-only?

No. The sml/projectile face applies to the project-name which is displayed before the file-path when you're inside a project. It does not apply to the minor mode indicator.

**Comment by swarnendubiswas** [comment]
Ok, I misunderstood the use of the font face. Thanks.
