### ISSUE TITLE
Powerline theme installation error

### ISSUE THREAD

**Issue by therockmandolinist** [Malabarba/smart-mode-line#189]
`M-x package-install smart-mode-line-powerline-theme` returns `https://melpa.org/packages/rich-minority-20151201.400.el: Not found`

**Comment by Malabarba** [comment]
Just refresh your package menu. ;-)

**Comment by therockmandolinist** [comment]
This was correct! A couple of things though, is this designed to work with terminal emacs (running osx)? I tried, but got question mark symbols in my mode line. After I tried to undo this and delete the theme, I saw it changed my init file and I'm now getting `Symbol's function definition is void: powerline-current-separator`. Sorry to bother you, do you know how to fix this? (and/or make powerline work with a terminal)

**Comment by Malabarba** [comment]
Unfortunately no, it's not compatible with the terminal. 
I think the issue is that emacs accidentally saved the theme options to your custom-set-variables. Look for entries in your custom-set-variables referencing powerline and delete those entries.
