### ISSUE TITLE
change the evil indicator color based on evil state?

### ISSUE THREAD

**Issue by zeltak** [Malabarba/smart-mode-line#195]
hi just discovered SML and im in love ;-)

was using space line before and it had that neat feature where the evil indicator color changed based on evil state. is that anyhow possible with SML?

thx alot for you amazing work (and awesome blog which i have been following for years !)

Z

**Comment by hisnawi** [comment]
Any updates on this?

**Comment by Malabarba** [comment]
It's certainly possible, but I don't really know how evil so works so it's hard to provide an answer

**Comment by Malabarba** [comment]
What I can say is that you need to look into the evil indicator elisp code and wrap that in a :propertize to add faces depending on its value.

**Comment by afldcr** [comment]
Simpler than that, just customize `evil-XXX-state-tag`, where XXX is an evil-state. Smart mode line respects it.

```elisp
(setq evil-normal-state-tag (propertize " <I> " 'face '((:foreground "#0ff"))))
```

**Comment by hisnawi** [comment]
Thanks afldcr, that is exactly what I needed up doing. Forgot to come back and post my code. Here it is:

```
    ;; Color the evil tag - colors taken from spaceline
    (setq evil-normal-state-tag   (propertize " <N> " 'face '((:background "DarkGoldenrod2" :foreground "black")))
          evil-emacs-state-tag    (propertize " <E> " 'face '((:background "SkyBlue2"       :foreground "black")))
          evil-insert-state-tag   (propertize " <I> " 'face '((:background "chartreuse3"    :foreground "black")))
          evil-replace-state-tag  (propertize " <R> " 'face '((:background "chocolate"      :foreground "black")))
          evil-motion-state-tag   (propertize " <M> " 'face '((:background "plum3"          :foreground "black")))
          evil-visual-state-tag   (propertize " <V> " 'face '((:background "gray"           :foreground "black")))
          evil-operator-state-tag (propertize " <O> " 'face '((:background "sandy brown"    :foreground "black"))))

```

**Comment by Malabarba** [comment]
Great!
