### ISSUE TITLE
[SERIOUS BUG] Reproducible- using  (sml/setup) in my init.org makes init.org freeze emas

### ISSUE THREAD

**Issue by zeltak** [Malabarba/smart-mode-line#196]
Hi

while i really love SML i currently cant seem to be using it :) 

i have a weird issue where when using  (sml/setup) in my init.org it makes init.org freeze emacs to the point i cant use emacs anynore. other .org files seem to not be affected.

any clue? would be very happy to help debug this

kind regards!

Z

**Comment by Malabarba** [comment]
Hi there, sorry for the silence. Are you still having this problem?
You could try running `M-x sml/setup` only after emacs has finished starting, see if it makes a difference.
If it's still a problem, the following method helps to debug why emacs is hanging: 

1. Do `M-x toggle-debug-on-quit`.
2. Reproduce the hang (or wait for it to happen)
3. Hit `C-g` while it's hanged.

You'll get a backtrace you can paste here.

**Comment by zeltak** [comment]
Hi again

Ok so have not been using SML since Jan since it froze emacs. tried now with updated emacs, packages etc and it seems to not freeze emacs, yet i, still getting an error:

```
Error (use-package): smart-mode-line :config: Wrong type argument: listp, t
```

i think this is a different error than last time

here is my current conf:

```
      (use-package smart-mode-line
       :ensure t
       :config
      (sml/setup)


      (setq sml/theme 'respectful)

        (add-to-list 'rm-blacklist " yas")
        (add-to-list 'rm-blacklist " super-save")
        (add-to-list 'rm-blacklist " Helm")
        (add-to-list 'rm-blacklist " Undo-Tree")
        (add-to-list 'rm-blacklist " Rbow")
        (add-to-list 'rm-blacklist " h")
        (add-to-list 'rm-blacklist " VHl")
        (add-to-list 'rm-blacklist " V")
        (add-to-list 'rm-blacklist " Wrap")
        (add-to-list 'rm-blacklist " WK")
 
   ;;    change abbrv to user defined 



       force only filename to display
          (setq sml/directory-truncation-string "")

 ;; Color the evil tag - colors taken from spaceline
    (setq evil-normal-state-tag   (propertize " <N> " 'face '((:background "DarkGoldenrod2" :foreground "black")))
          evil-emacs-state-tag    (propertize " <E> " 'face '((:background "SkyBlue2"       :foreground "black")))
          evil-insert-state-tag   (propertize " <I> " 'face '((:background "chartreuse3"    :foreground "black")))
          evil-replace-state-tag  (propertize " <R> " 'face '((:background "chocolate"      :foreground "black")))
          evil-motion-state-tag   (propertize " <M> " 'face '((:background "plum3"          :foreground "black")))
          evil-visual-state-tag   (propertize " <V> " 'face '((:background "gray"           :foreground "black")))
          evil-operator-state-tag (propertize " <O> " 'face '((:background "sandy brown"    :foreground "black"))))


       )
```

thx!

Z

**Comment by Malabarba** [comment]
That new bug sounds more like a an issue with how you're using `use-package`. I don't personally use it, so I can't help you there.

On a side note, I can say that you need to set `sml/theme` *before* running `sml/setup`, otherwise it won't take.
