### ISSUE TITLE
Freeze in term with latest emacs sources

### ISSUE THREAD

**Issue by antoine-levitt** [Malabarba/smart-mode-line#198]
Hi,

With emacs from latest git, running sml/setup and then M-x term freezes emacs. Might be related to https://lists.gnu.org/archive/html/bug-gnu-emacs/2016-10/msg00703.html.

**Comment by peterwvj** [comment]
I'm experiencing the same if I run `M-x ansi-term`.

**Comment by Mihara** [comment]
Same here.

For what it's worth, interrupting the frozen emacs with SIGUSR2 produces this debug output:

```
Debugger entered--entering a function:
* sml/-this-buffer-changed(1 5 0)
  file-accessible-directory-p("/home/mihara/.emacs.d/lisp/")
  cd-absolute("/home/mihara/.emacs.d/lisp")
  cd("/home/mihara/.emacs.d/lisp")
  #[(string) "\306\232\203\307\207\310H\311U\2031\312\313\314#\312\313	T#\314	O\315	T\nO!\fB\211,\207\310H\316U\203@\317\314\320O!\207\307\207" [string first-colon second-colon filename fileline term-pending-frame "" t 0 26 string-match ":" 1 string-to-number 47 cd nil] 4]("//home/mihara/.emacs.d/lisp")
  ad-Advice-term-command-hook(#[(string) "\306\232\203\307\207\310H\311U\2031\312\313\314#\312\313	T#\314	O\315	T\nO!\fB\211,\207\310H\316U\203@\317\314\320O!\207\307\207" [string first-colon second-colon filename fileline term-pending-frame "" t 0 26 string-match ":" 1 string-to-number 47 cd nil] 4] "//home/mihara/.emacs.d/lisp")
  apply(ad-Advice-term-command-hook #[(string) "\306\232\203\307\207\310H\311U\2031\312\313\314#\312\313	T#\314	O\315	T\nO!\fB\211,\207\310H\316U\203@\317\314\320O!\207\307\207" [string first-colon second-colon filename fileline term-pending-frame "" t 0 26 string-match ":" 1 string-to-number 47 cd nil] 4] "//home/mihara/.emacs.d/lisp")
  #[128 "\300\301\302#\207" [apply ad-Advice-term-command-hook #[(string) "\306\232\203\307\207\310H\311U\2031\312\313\314#\312\313	T#\314	O\315	T\nO!\fB\211,\207\310H\316U\203@\317\314\320O!\207\307\207" [string first-colon second-colon filename fileline term-pending-frame "" t 0 26 string-match ":" 1 string-to-number 47 cd nil] 4] nil] 5 nil]("//home/mihara/.emacs.d/lisp")
  term-emulate-terminal(#<process *ansi-term*> "//home/mihara/.emacs.d/lisp
\n")
```

Is there any hope someone more knowledgeable can get this sorted out? This is a real pain.

**Comment by Malabarba** [comment]
Sorry for the silence. I'll try to have a look at it this week. It's weird that file-accessible-directory-p is triggering sml hooks.

**Comment by antoine-levitt** [comment]
For what it's worth, temporary workaround:

(ad-deactivate 'term-command-hook)
(ad-deactivate 'term-handle-ansi-terminal-messages)

**Comment by erreina** [comment]
Any further progress on this?

**Comment by Malabarba** [comment]
No progress. The term advices used by sml are just meant to keep track of the shell's CWD. If it's causing hangs then I'm not opposed to simply disabling this feature. 
Is this still a problem with latest Emacs?

**Comment by apauzies** [comment]
Yes, I have the issue with:

```GNU Emacs 26.0.90 (build 1, x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1911)) of 2017-10-11```

```
Debugger entered--returning value: nil
  sml/-this-buffer-changed(1 5 0)
  cd-absolute("/Users/alex")
  cd("/Users/alex")
  #f(compiled-function (string) #<bytecode 0x40551ba3>)("//Users/alex")
  ad-Advice-term-command-hook(#f(compiled-function (string) #<bytecode 0x40551ba3>) "//Users/alex")
  apply(ad-Advice-term-command-hook #f(compiled-function (string) #<bytecode 0x40551ba3>) "//Users/alex")
  #f(advice-wrapper :around #f(compiled-function (string) #<bytecode 0x40551ba3>) ad-Advice-term-command-hook)("//Users/alex")
  term-emulate-terminal(#<process *ansi-term*> "\032//Users/alex\015\n\033[?1034h\033[01;35malex@imac\033[01;36m:~ $\033[00m ")
```

**Comment by Malabarba** [comment]
Thanks for all the info.
I haven't been able to spend as much time as I'd like on package maintenance, so I welcome anyone who'd like to take a crack at this. 
Meanwhile, I'll keep trying to find some time for it, and apologising for the delays.

**Comment by a-schaefers** [comment]
The workaround causes an annoying init warning message to pop up, I hope we can resolve this better

**Comment by phil-s** [comment]
You shouldn't be deactivating *all* advice if you know that there are *specific* pieces of advice which are responsible -- who knows what else you've disabled.

Use `ad-remove-advice` for the specific advice, and then `ad-activate` to make it take effect.

**Comment by Malabarba** [comment]
Hi everyone.
I've removed both advices now. Let me know if it solves the issue as soon as Melpa rebuilds (I tried reproducing the issue here but it didn't happen for me).

**Comment by daviderestivo** [comment]
Hi Arthur,

it works for me now.

Thanks and regards,
Davide
