### ISSUE TITLE
Error during redisplay: sml/generate-minor-modes

### ISSUE THREAD

**Issue by mbtuckersimm** [Malabarba/smart-mode-line#200]
sml version is 2.10, emacs version is 25.1.1.

I keep getting the following message displayed in my `*Messages*` buffer:

```
Error during redisplay: (eval (sml/generate-minor-modes)) signaled (wrong-type-argument number-or-marker-p "full") [57 times]
```

The number of times is variable, this example was just chosen at random. I have the following line in my `init.el`, which may be the culprit:

```
(setq sml/mode-width "full")
```

Is that correct? I tried without the quotes but it gave an error.

If I execute `(sml/generate-minor-modes)` from the scratch buffer, it enters the debugger and I get the following backtrace:

```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p "full")
  -("full" 0 0)
  sml/generate-minor-modes()
  eval((sml/generate-minor-modes) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by plu5** [comment]
It should be a symbol:
```emacs-lisp
(setq sml/mode-width 'full)
```

when in doubt, use customise (`M-x customize-variable sml/mode-width`) and see how it sets it

**Comment by mbtuckersimm** [comment]
That did it. Should have thought of using customize. That's a great trick which I will certainly keep in mind in the future. Thanks so much for your help and for your work making this great package.
