### ISSUE TITLE
Graphical artifacts in line-number-mode

### ISSUE THREAD

**Issue by DiegoVicen** [Malabarba/smart-mode-line#202]
I experience some strange graphical errors in the line-number-mode, like in this image (when moving from line 495 to line 498):

<img width="365" alt="screen shot 2017-04-28 at 16 17 18" src="https://cloud.githubusercontent.com/assets/7013448/25547902/15633a3c-2c6a-11e7-8dc4-642d4f91979d.png">

My guess is that there is some kind of rendering problem with it, because the successful workaround I found is to add a whitespace at the very beginning of the `mode-line-format` variable, so there is nothing right below the fringe. I don't know if there is a way to detect if the fringe is on, so the package can add the padding automatically to prevent the artifacts.

I'm running in Cocoa specific Emacs.app version 25.1.1 in macOS 10.12.4, with MELPA's `smart-mode-line` 20160818.508, in case it is relevant.

**Comment by Malabarba** [comment]
That's strange indeed, but it's more likely to be a rendering bug with your Emacs compilation. I get other types of rendering glitches with Emacs sometimes (not on the mode-line).
