### ISSUE TITLE
term gets stuck if smart-mode-line is loaded.

### ISSUE THREAD

**Issue by tomasorti** [Malabarba/smart-mode-line#210]
Steps to reproduce it:
- Start Emacs with: `emacs -Q -mm`
- Eval buffer or region with the following code:
```
(setq package-enable-at-startup nil)
(setq sml/no-confirm-load-theme t)
(package-initialize)
(sml/setup)
```
- Execute a terminal with `M-x term` and in the minibuffer choose `Run program: /bin/bash`

Terminal will get stuck and Emacs will not respond.
The only thing I could do is `kill -9` Emacs from a Linux terminal.

I am using **Emacs 27.0.50** and `smart-mode-line` Version **20171013.849**

**Comment by akater** [comment]
Confirmed with 26.0.90 as well, same sml version.

**Comment by Malabarba** [comment]
Closing as duplicate of #198
