### ISSUE TITLE
Inhibits text properties on mode-line-process?

### ISSUE THREAD

**Issue by phil-s** [Malabarba/smart-mode-line#214]
wrt: https://github.com/magit/magit/pull/3314#issuecomment-356068973

Recent changes to Magit add text properties to `mode-line-process` in order to provide process status information to the user, but when `smart-line-mode` is enabled, none of those properties are effective.

In my test in that other thread, I triggered a Git error by attempting to rebase in Magit with unstaged changes present, and I could then observe that the intended text properties *are* present:

    (with-current-buffer "*magit: .emacs.d"
      mode-line-process)

> #(" git rebase" 1 11 (mouse-face highlight keymap (keymap (mode-line keymap (mouse-1 . magit-process-buffer))) help-echo "Cannot rebase: You have unstaged changes.
Please commit or stash them.
> 
> mouse-1: Show process buffer" face magit-mode-line-process-error))

However:

* The faces are not apparent
* The `help-echo` tooltip doesn't appear
* The keymap for mouse-1 doesn't work

**Comment by Malabarba** [comment]
Oops, I replied to that other thread before realising you had posted an issue here.

It's probably because sml wraps its own properties around mode-line-process. Back when I wrote it (years ago) I wasn't aware of any package that added properties to this string. I wouldn't mind a PR to fix that issue, but it would have to be a solution that doesn't sacrifice current functionality.

**Comment by phil-s** [comment]
I can confirm that commenting out the following restores the Magit functionality:

     ;; Color the mode line process
     ((or (equal el '("" mode-line-process))
          (equal (car (cdr-safe el)) '("" mode-line-process)))
      `(:propertize ("" mode-line-process) face sml/process))

As `smart-mode-line` is setting its own face, we might aim to make that conditional on `mode-line-process` not having a face already?

Magit only propertizes the `mode-line-process` string from the second char onwards, because the first char is a separator space, and it looks bad if the face is customized to set a background colour when the separator is included. Hence for this particular use-case we can detect a face with:

    (get-text-property 1 'face mode-line-process)

Provided `mode-line-process` is a string with length > 0.

As `mode-line-process` could be any mode line construct, I concluded that we need to call `format-mode-line` on it before trying to inspect it.

My initial attempt looks like this:

    ;; Color the mode line process
    ((or (equal el '("" mode-line-process))
         (equal (car (cdr-safe el)) '("" mode-line-process)))
     '(:eval (let ((text (format-mode-line mode-line-process)))
               (cond ((string= text "")
                      "")
                     ((get-text-property 1 'face text)
                      text)
                     (t
                      (propertize text 'face 'sml/process))))))

I was briefly hoping to use `text-property-any` to check for a `face` property anywhere in the string (as the separator space assumption is quite hacky), but that function can only search for *specific* values, rather than *any* value. Is there a better option than iteratively calling `next-property-change` and checking `get-text-property` ?

**Comment by Malabarba** [comment]
Yes, that code looks fine, I think.
WRT to `next-property-change`, you should be able to use `next-single-property-change` to scan for the presence of a specifica property in a single function call.

**Comment by phil-s** [comment]
Thanks for that pointer. I think we actually want `next-single-char-property-change` based on the docstrings, as it sounds like `next-single-property-change` will return `nil` when the property is constant all the way to the end of the string.

**Comment by tarsius** [comment]
I had a similar issue in `moody` and the fix turned out to be as easy as replacing a certain instance of `propertize` with `add-face-text-property`.

**Comment by phil-s** [comment]
Thanks for the ping :)

Ah, interesting. I can see `(add-face-text-property 0 (length string) face nil string)` in https://github.com/tarsius/moody/blob/master/moody.el

I assume the difference between the approaches is:

> If any text in the region already has a non-nil ‘face’ property, those
> face(s) are retained.  This is done by setting the ‘face’ property to
> a list of faces, with FACE as the first element (by default) and the
> pre-existing faces as the remaining elements.
