### ISSUE TITLE
Not compatible with eamcs-26.1 term-mode

### ISSUE THREAD

**Issue by liyunteng** [Malabarba/smart-mode-line#226]
will cause term-mode hung.
comment
"(defadvice term-command-hook (after sml/term-advice-1 activate)
   (sml/generate-buffer-identification))"
will work correct.

**Comment by sandinmyjoints** [comment]
I'm seeing the same issue.

**Comment by azzamsa** [comment]
Thank you for this. Last month I thought it was because of changes in emacs 26.1, turn out it comes from smart-mode-line.

Upgraded smart-mode-line today, and it works fine. no hang. but emacs screen blink every time I press keyboard key.

**Comment by Malabarba** [comment]
The latest version on Melpa removed the problematic line. So it should be working well now.
