### ISSUE TITLE
How can I change the out of focus color?

### ISSUE THREAD

**Issue by mrbig033** [Malabarba/smart-mode-line#228]
I couldn't find the variable to change the colors when the window loses focus.

**Comment by articuluxe** [comment]
The mode line, and its active/inactive faces, is usually customized via the current theme.

**Comment by Malabarba** [comment]
It's the usual `mode-line-inactive` face. Just call M-x customize-face
and type in mode-line-inactive.

**Comment by Malabarba** [comment]
closing for now. Comment if you need more help.
