### ISSUE TITLE
Atom-one-dark theme for smart-mode-line

### ISSUE THREAD

**Issue by daviderestivo** [Malabarba/smart-mode-line#230]
Hi Artur,
I've created a [new smart-mode-line theme](https://gist.github.com/daviderestivo/f739b60fde1589fee00ab2d8d0ebc18d) that fits the [atom-one-dark](https://github.com/jonathanchu/atom-one-dark-theme) one. If you plan  to expand the current sml available themes with new ones, feel free to include it ... I can open a pull request.

![screen shot 2018-08-04 at 14 52 21](https://user-images.githubusercontent.com/16867449/43676684-0457f78e-97f6-11e8-9ba7-49b46dab8bca.png)

Thanks in advance and regards,
Davide

**Comment by Malabarba** [comment]
Hi David,

Have you thought about submitting it as a package of your own? That would make it easier for you to manage it, and I'd be glad to mention it on the Readme.

All you'd need to do is list sml as a dependency:

    ;; Package-Requires: ((emacs "24.3") (smart-mode-line "2.10"))

**Comment by daviderestivo** [comment]
Hi Artur,

I will try out to make my own package and publish it on Melpa :). Thanks again for this nice package (smart-mode-line) you have build.

I guess you can close this issue.

Regards,
Davide

**Comment by daviderestivo** [comment]
Hi Artur,

I've created a new packages for the sml atom-one-dark-theme. You can find it [here](https://github.com/daviderestivo/smart-mode-line-atom-one-dark-theme). A [new pull requests](https://github.com/melpa/melpa/pull/5732) has been issued for the inclusion into the Melpa repository. 

It would be nice if you can add a link into the smart-mode-line README.

Regards,
Davide

**Comment by Malabarba** [comment]
Cool! I'll add to the readme when I get home.

**Comment by Malabarba** [comment]
Done! Thanks for the nice theme!
