### ISSUE TITLE
Errors during redisplay

### ISSUE THREAD

**Issue by ardpp** [Malabarba/smart-mode-line#231]
Hi! I started getting errors which are displayed as follows in the Messages buffer

```
Error during redisplay: (eval (sml/generate-buffer-identification-if-necessary)) signaled (void-variable sml/projectile-replacement-format)
Error during redisplay: (eval (sml/generate-buffer-identification)) signaled (void-variable sml/projectile-replacement-format) [28 times]
Error during redisplay: (eval (sml/generate-buffer-identification-if-necessary)) signaled (void-variable sml/projectile-replacement-format)
Error during redisplay: (eval (sml/generate-buffer-identification)) signaled (void-variable sml/projectile-replacement-format) [16 times]
```
I can reproduce this with my "normal" configuration as well as with `emacs -Q` (the above errors are pasted from Messages buffer from the latter). 

`smart-mode-line` is the newest from Melpa.
emacs version  is GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.1) of 2018-09-25
I am not using `projectile`
Let me know if I can provide more useful information.

**Comment by ReichKV** [comment]
I have the same problem. Emacs version 26.1

**Comment by frankcreed** [comment]
when I comment out line 582 below, all the above error messages go away
Emacs 26.1, *not* using or loading 'projectile

(defcustom sml/prefix-face-list '((":SU:" sml/sudo)
                                  (":G" sml/git)
                                  ;; (sml/projectile-replacement-format sml/projectile)
                                  ("" sml/prefix))

**Comment by Malabarba** [comment]
Should be fixed next time melpa rebuilds. Let me know if it works.

**Comment by frankcreed** [comment]
The fix works fine for me - thanks for the speedy response!

**Comment by ardpp** [comment]
Fixed for me as well! Thanks a lot!
