### ISSUE TITLE
Syntax help/Feature request to support ,(upcase \1) type of syntax in regex replacement

### ISSUE THREAD

**Issue by kaushalmodi** [Malabarba/smart-mode-line#29]
Hi Bruce,

Is this kind of regex replacement supported?

M-x replace-regexp
  Replace regexp:  (\w+)
  Replace regexp with:  \,(capitalize \1)

If so, I am unable to get the syntax right.

I am trying the following:

<code>(add-to-list 'sml/replacer-regexp-list '("/projects/\\([a-z0-9_]\\{3\\}\\).*/.*" ":\\,(upcase \\1):"  ) t )</code>

Here I want to take the first 3 chars of the project and upcase that to create a tag.
If the project name is "macaroni", I'd like the tag to be ":MAC:".

From the example in smart-mode-list.el, I figured that the above should work if I replaced "\" with "\\" in the regex expressions. But it doesn't work.

**Comment by art-solopov** [comment]
Thank you @Malabarba! Your response helped me a lot. Reference it in the docs and/or wiki maybe?

**Comment by Malabarba** [comment]
@art-solopov Yep, that would be good. Would you like to try a Pull Request? :-)

**Comment by art-solopov** [comment]
@Malabarba I'll do my best!
