### ISSUE TITLE
incorrect filename displayed

### ISSUE THREAD

**Issue by aspiers** [Malabarba/smart-mode-line#44]
When I open a file `~/org/TODO.org`, sml displays it in the modeline as `~/org/org/TODO.org` - see attached screenshot:

![sml-org-bug](https://f.cloud.github.com/assets/100738/1748655/9e970a96-64d0-11e3-8531-73aced03c2b5.png)

Potentially relevant info:

```
sml/replacer-regexp-list is a variable defined in `smart-mode-line.el'.
Its value is (("^~/\\.emacs\\.d/" ":ED:")
 ("^/sudo:.*:" ":SU:")
 ("^~/crowbarP/barclamps/\\(.+\\)/" ":CPB:\\1:"))

Original value was 
(("^~/\\.emacs\\.d/" ":ED:")
 ("^/sudo:.*:" ":SU:"))
```

**Comment by MaksVal** [comment]
Hi! Thanks for your job! :)
I have a similar problem.
If I use toogether with next code:
```
(require 'airline-themes)
(require 'powerline)
(require 'smart-mode-line)
```
Then I see this
![image](https://user-images.githubusercontent.com/10114447/26918593-52402550-4c3b-11e7-97c2-89f34d9f13a8.png)

I like your plugin and I like this: https://github.com/AnthonyDiGirolamo/airline-themes
This is my problem:
![image](https://user-images.githubusercontent.com/10114447/26918683-b193ec76-4c3b-11e7-86f2-0202b04c7ea1.png)
![image](https://user-images.githubusercontent.com/10114447/26918736-d7b701ae-4c3b-11e7-850f-4d8674c0623f.png)


What do you think? Thanks!

**Comment by Malabarba** [comment]
Hi @MaksVal, have you tried the instructions on this comment? https://github.com/Malabarba/smart-mode-line/issues/44#issuecomment-30578329
