### ISSUE TITLE
Hidden modes does not work anymore

### ISSUE THREAD

**Issue by 4DA** [Malabarba/smart-mode-line#82]
sml doesn't hide minor mode names from `sml/hidden-modes' variable anymore.

git HEAD: 37545b088b8c0972eec799a6096e2b07e6972ccd

thanks.

**Comment by Malabarba** [comment]
Hi there, sorry for dropping this for so long, things have been hectic.
Do you still have this problem? The final screenshot you posted actually looks fine. Is there anything unexpected in it?

**Comment by 4DA** [comment]
Hi. I think the issue is gone.
Thanks.

**Comment by Malabarba** [comment]
Good to know!
