### ISSUE TITLE
Problem with default sml theme + emacs daemon

### ISSUE THREAD

**Issue by thiagowfx** [Malabarba/smart-mode-line#86]
I'm using smart-mode-line version 2.5.3 with Emacs 24.3.1.

My `.emacs` contain

```
(when (locate-library "smart-mode-line")
  (sml/setup))
```

This always worked okay. However today, after upgrading my packages with package.el (M-x list-packages, then U x), I cannot start emacs server automatically anymore, because emacs prompts me to load the theme (security measures).

---

Here is how to reproduce it:

Put

```
(when (locate-library "smart-mode-line")
  (sml/setup))
```

somewhere in your .emacs file. Then, start emacs as a server:

`emacs --daemon`

You'll see some messages from other configs, then a message in your terminal emulator about sml:

`Loading a theme can run Lisp code.  Really load? (y or n)`

Even after choosing y, the startup hangs. If I start emacs normally instead (as `$ emacs`), the same prompt will appear, this time in the minibuffer. After choosing y, it works, but this is annoying anyway.

Summarizing: this prompt shouldn't exist. Since everything worked okay before my upgrade, I believe this is strongly related to the 'automatic' theme feature.

I can guarantee this is from sml (and not other package) because when I comment out these two lines, I don't get this prompt.

**Comment by DGrady** [comment]
I realize this is pretty old, but I'm running in to the same problem and wondered if there's any additional information about this. While trying to debug, it seems like the problem might be related to having custom faces defined. With the following in my `~/.emacs.d/init.el` file, running `emacsclient` from a terminal will trigger the message about loading themes and hang:

```
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:family "Monaco"))))
 )
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-safe-themes
   (quote
    ("a27c00821ccfd5a78b01e4f35dc056706dd9ede09a8b90c6955ae6a390eb1c1e" default))))

(require 'package)
(package-initialize)
(sml/setup)
```

But if you comment out the `custom-set-faces` form, everything works as expected. This is using `smart-mode-line` version 20180801.341 and this Emacs:

> This is GNU Emacs 26.1 (build 1, x86_64-apple-darwin16.7.0, NS appkit-1504.83 Version 10.12.6 (Build 16G1408))
 of 2018-06-06

**Comment by DGrady** [comment]
After some additional fiddling around with this, it seems like what's going on (at least for me) is that with the default setting of `sml/theme` as `automatic`, the presence or absence of a custom face causes smart-mode-line to choose a different theme when emacs is started in daemon mode. If I don't specify a custom face, then smart-mode-line chooses the light theme, which is marked as safe. If I do specify a custom face, then smart-mode-line chooses the dark theme. To fix this problem, I can either add all the smart-mode-line themes to the safe themes list, or I can `(setq sml/theme 'light)` before calling `(sml/setup)`.

Hope this helps anyone else who runs across this behavior!
