### ISSUE TITLE
sml/vc edited face does not change after commit

### ISSUE THREAD

**Issue by panaak** [Malabarba/smart-mode-line#95]
hi,
am i doing something wrong or this is normal? here's the deal:
- i open a file in a clean git branch - sml/vc face is blue - not edited
- i edit the file and save it - sml/vc face changes to orange - edited
- i commit the change
- go back to the original buffer - sml/vc face stays orange - edited, but it should switch to blue, shouldn't it?
  (magit-auto-revert mode t)
  (global-auto-revert-mode t)

i have to switch branches back and forth or revert-buffer manually to make the face change..

-mp-

**Comment by zwb-ict** [comment]
@panaak Thank you. I tried as you did. Now it works well with magit now!
